### ISSUE TITLE
it does't ask for bump type

### ISSUE THREAD

**Issue by lili21** [changesets/changesets#1017]
## Affected Packages

pkg:@changesets/cli

## Problem

when running `changeset add`, it does't ask for bump type, and default to major bump

![image](https://user-images.githubusercontent.com/4456380/203750732-c94e203f-1290-405b-9cc7-49ea86c69981.png)

**Comment by lili21** [comment]
Can anyone help with this?

**Comment by benelori** [comment]
This is happening for me as well, for now I'm manually updating the temporary changeset that is generated after the `add` command

**Comment by lili21** [comment]
@benelori Thanks. did not know that before.
