### ISSUE TITLE
meow not found

### ISSUE THREAD

**Issue by unional** [changesets/changesets#1032]
## Problem

Getting this error when using changeset

```sh
> @ cs /Users/hwong/unional/just-func-typescript
> changeset

/Users/hwong/unional/just-func-typescript/.pnp.cjs:22990
    throw firstError;
    ^

Error: Your application tried to access meow, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: meow
Required by: /Users/hwong/unional/just-func-typescript/node_modules/.pnpm/@changesets+cli@2.25.2/node_modules/@changesets/cli/dist/
```

This issue pops up and I can't use changeset.

I think this is an issue on pnpm, but opening the issue there also for cross reference just in case.

## Proposed solution

Will further investigate.

Using pnpm 7.18.2

**Comment by Andarist** [comment]
Hm, it is our dependency though: https://github.com/changesets/changesets/blob/e02a0c4b7ec869d21b10495138d9fb193b213917/packages/cli/package.json#L57

Could you share a repro case for this problem?

**Comment by unional** [comment]
Yes, I agree. That's why I think it is `pnpm` issue. See the linked issue.

Here is the repo: https://github.com/justland/just-func-typescript

It is working in Windows, but not in macOS.

**Comment by bluwy** [comment]
meow has been removed in https://github.com/changesets/changesets/pull/1392. I don't know if it still happens for other dependencies, but the issue seems quite old that the latest pnpm version should probably work now.

**Comment by Maliksb11** [comment]
ok
