### ISSUE TITLE
Retrieve `publish` step from bolt - remove bolt dependency

### ISSUE THREAD

**Issue by Noviny** [changesets/changesets#105]
Currently we are installing all of bolt basically just so we can use its recursive calls to NPM publish - and the error messaging around publish tends to be pretty poor.

This ticket vaguely covers:

- [ ] publish publish script as a changesets package
- [ ] remove `bolt` as a dependency from changesets
- [ ] Improve error messaging/CLI options of publish. Biggest ones are: Do not say `success Packages Failed To Publish` and if not in CI, prompt when we get a 2FA error for the user to enter their 2FA code instead of failing

however these may be done in separate steps/PRs

**Comment by mitchellhamilton** [comment]
Closed via #106
