### ISSUE TITLE
Changeset publish doesn't work on private npm registry

### ISSUE THREAD

**Issue by igoldny** [changesets/changesets#1082]
## Affected Packages

@changesets/cli

## Problem

I'm using Changesets on our GitHub Enterprise with Jenkines,
I cannot use github actions bot and have to setup publish workflow manually.

The problem is with using `yarn changeset publish `
i get the following error:
```
🦋  error an error occurred while publishing @[my-package-name]: ENEEDAUTH This command requires you to be logged in to https://my.registry.com/artifactory/api/npm/
🦋  error You need to authorize this machine using `npm adduser`

🦋  error npm ERR! code ENEEDAUTH

🦋  error npm ERR! need auth This command requires you to be logged in to https://my.registry.com/artifactory/api/npm/

🦋  error npm ERR! need auth You need to authorize this machine using `npm adduser`

🦋  error {

🦋  error   "error": {

🦋  error     "code": "ENEEDAUTH",

🦋  error     "summary": "This command requires you to be logged in to https://my.registry.com/artifactory/api/npm/",

🦋  error     "detail": "You need to authorize this machine using `npm adduser`"

🦋  error   }

🦋  error }

🦋  error 

🦋  error npm ERR! A complete log of this run can be found in:

🦋  error npm ERR!     /root/.npm/_logs/2023-01-25T12_23_58_554Z-debug-0.log

🦋  error packages failed to publish:

error Command failed with exit code 1.

yarn run v1.22.15

$ /Jenkins/builds/6/node_modules/.bin/changeset publish
```

i am currently using `lerna publish` and it works.
as for authentication i have `.npmrc` file with `_auth=[token]`
also tried using the same structure you use in github bot:
`//my.registry.com/artifactory/api/npm//:_authToken=[token]`
but still same error...

how can i publish on private npm registry?

**Comment by citrusjunoss** [comment]
Add a .npmrc file under the root directory with the following content.

```bash
registry=http://my.registry.com
```

**Comment by igoldny** [comment]
I already have `.npmrc` with registry as you mentioned in the project root directory.
my `.npmrc` content:
```
registry=http://my.registry.com
@private/registry=http://my.registry.com/private
_auth=[token]
```
this option currently works with `lerna publish`
switching to changeset publish return the above error...

**Comment by Andarist** [comment]
I would try manually those:
1. `npm publish path/to/pkg --json`
2. `npm publish path/to/pkg --json --no-workspaces`

It would be helpful to learn if any of those succeed (Changesets is currently doing 1 when publishing with `npm`)

**Comment by igoldny** [comment]
Got the same error with `npm publish ` as well.
After manually running of `npm login ` it works.
Wonder what `lerna publish` is doing to make it work with `.npmrc` only?
Using `npm login ` in CI doesn't feel like the right direction...

**Comment by Andarist** [comment]
> Got the same error with npm publish  as well.

Hm, this is a little bit surprising - I have expected one of those to work. What about those?
1. `cd path/to/pkg && npm publish --json`
2. `cd path/to/pkg && npm publish --json --no-workspaces` 

Note that I'm assuming that `.npmrc` exists in the **root** and not in the published package.

> Wonder what lerna publish is doing to make it work with .npmrc only?

That could probably be checked but at the same time, I'm not sure if I want to invent some Changesets conventions here (or reuse the Lerna ones). 

> Using npm login  in CI doesn't feel like the right direction...

Yes, it's not a solution here.

**Comment by Andarist** [comment]
Have you tried writing to `$HOME/.npmrc`? OTOH, this is probably what `npm login` does under the hood. Since you control your environment though... maybe that could help you for now. I'm still very much interested in learning how to make it work with the `./project_root/.npmrc`

**Comment by igoldny** [comment]
I got `.npmrc` at the root and bash symbolic link on each package folder.
and my `.npmrc` looks a bit different since we use private npm registry
```
registry=https://my.registry.com
//my.registry.com/:_password=[_password]
//my.registry.com/:username=[user]
//my.registry.com/:email=[email]
//my.registry.com/:always-auth=true
```

**Comment by igoldny** [comment]
moving to `:_authToken ` format works with those 4 variants but i guess it dosn't support `:_password ` format out of the box, maybe lerna has some extra code that generate token using username and password 🤔

**Comment by Andarist** [comment]
I think I've seen those things (`:_password` etc) mentioned in the npm tests and stuff - so I think it should "just work". But I have never seen those being used so I'm not sure if there are any other preconditions for this. It would be rather weird if Lerna would have to generate tokens on their own (if that's even possible).

If you would setup a a repo in which I could test this out with Lerna... then I could try to debug this

**Comment by igoldny** [comment]
@Andarist you right it wasn't it, after deep dive into the root cause i found that the registry i'm getting from our private npm includes port, looks something like this (i didn't even thought it was important to mention):
```
registry=https://my.registry.com:443/
//my.registry.com/:_password=[_password]
//my.registry.com/:username=[user]
//my.registry.com/:email=[email]
//my.registry.com/:always-auth=true
```

the root cause is the publish registry URL in either the cli or package.json gets processed through new URL() which removes common ports, and they use a different code snippet for encoding/decoding the registry scope, so it tries to match them, and it doesn't think it exists...

closing this issue, thank you so much for the support @Andarist you are awesome!

**Comment by Andarist** [comment]
Out of curiosity - do you happen to know why it was working for you with Lerna?

**Comment by igoldny** [comment]
yes, that's a good question, I'm not fully familiar lerna internals to answer that and from a glans search nothing came up...

**Comment by kavitalikesfajitas** [comment]
if for some ungodly unfortunate reason someone else stumbles upon this thread, 
You can specify the location of your .npmrc:
`--use-npmrc .npmrc` 

I was specifically trying to publish one package via workspaces and changeset.
I also had the unfortunate experience of using artifactory in this experience - if you're looking for that answer: https://stackoverflow.com/questions/70063404/publish-npm-package-to-jfrog-artifactory-using-github-action/79726786#79726786
