### ISSUE TITLE
Question: Bump support versions on older releases, bug fixes, patches etc.

### ISSUE THREAD

**Issue by dmi3y** [changesets/changesets#1131]
I have a question about ability to release bug fix/minor versions for older releases:

e.g there are two active releases `package@v1.0.0` and `package@v2.0.0`.

And there is a critical bug found.

Fixing it bumping `package@v2.0.0` -> `package@v2.0.1`.

What would be the strategy to port this bug fix on `package@v1.0.0` to bump it to `package@v1.0.1`?

And very similar situation if there is some feature needed to be introduced in `package@v1.0.0` and needing to bump it up to `package@v1.1.0`?

Thanks!

I was not able to find answer in documentation and that's why I'm asking it here, sorry if I missed it.

**Comment by maxkarkowski** [comment]
is there any new info about that?

**Comment by bluwy** [comment]
There's a similar issue being asked at https://github.com/changesets/changesets/issues/1019 as well. I'll close this in favour of that.
