### ISSUE TITLE
Expect changesets to run NPM related hook functions

### ISSUE THREAD

**Issue by duowb** [changesets/changesets#1145]
## Affected Packages

I am not sure...

Example: https://github.com/duowb/pnpm-changsets-monorepo-example

## Problem

1. Modify any content in the `package/a` ;
2. run changeset, select `@duobo/pkg-a`;
3. run changeset version.  Expected to output the content in packages/a/b. js, Because the script in package/a is listening for preversion
4. run changeset publish.  Expected to output the content in packages/a/a. js, Because the script in package/a is listening for prepublish

## Proposed solution

If I make a mistake, please guide me. thank you

**Comment by bluwy** [comment]
I wonder if this has something to do with https://github.com/changesets/changesets/issues/886, which perhaps the script runs but the logs are not logged.

**Comment by bluwy** [comment]
Looks like there's an issue already open at https://github.com/changesets/changesets/issues/982 that describes this. I'll close this in favour of that as it has a little more activity.
