### ISSUE TITLE
Error publish in Gitlab registry

### ISSUE THREAD

**Issue by jorgecasar** [changesets/changesets#1146]
## Affected Packages

pkg:cli

## Problem

I get this error publishing into Gitlab registry. I'm using [changesets-gitlab](https://github.com/un-ts/changesets-gitlab) in the pipelines, and it's works perfectly (git push included). But i can't publish to the Gitlab registry.

```
error an error occurred while publishing @[namespace]/[package-name]: ENEEDAUTH This command requires you to be logged in to https://gitlab.company.com/api/v4/packages/npm/ 
🦋  error You need to authorize this machine using `npm adduser`
🦋  error npm ERR! code ENEEDAUTH
🦋  error npm ERR! need auth This command requires you to be logged in to https://gitlab.company.com/api/v4/packages/npm/
🦋  error npm ERR! need auth You need to authorize this machine using `npm adduser`
🦋  error {
🦋  error   "error": {
🦋  error     "code": "ENEEDAUTH",
🦋  error     "summary": "This command requires you to be logged in to https://gitlab.company.com/api/v4/packages/npm/",
🦋  error     "detail": "You need to authorize this machine using `npm adduser`"
🦋  error   }
🦋  error }
🦋  error 
```
before script I run:

```
npm config set -- //$CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/packages/npm/:_authToken=$CI_JOB_TOKEN
npm config set @[namespace]:registry https://$CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/packages/npm/


Changesets didn't get the global config? Should I specify without namespace? This config is working in other project using semantic-releaase, and it works with npm publish.

**Comment by jorgecasar** [comment]
It was a configuration error.

**Comment by alshdotme** [comment]
Would you mind sharing your solution please? I'm struggling to get changesets to publish to my private gitlab registry

**Comment by tflanagan** [comment]
The `internalPublish` command is not quite working as you'd expect.

I am using `npm`.

In each `package.json`, specify the `publishConfig` object. `pnpm` expects `registry`, but `npm` expects `@org:registry`. The `internalPublish` command could be monkey patched by replace line 704 in `cli.cjs.dev.js`

```
const registry = (_packageJson$publishC = packageJson === null || packageJson === void 0 ? void 0 : (_packageJson$publishC2 = packageJson.publishConfig) === null || _packageJson$publishC2 === void 0 ? void 0 : _packageJson$publishC2.registry || _packageJson$publishC2[packageJson.name.split('/')[0] + ':registry']) !== null && _packageJson$publishC !== void 0 ? _packageJson$publishC : process.env.npm_config_registry;
```

With this change I was able to get it to detect the correct registry, but I was then receiving an error with the PUT request.

Ultimately, I created a turborep task that goes through the individual `packages/*` folders and runs `npm publish` . This works without an issue.

**Comment by kikar** [comment]
> It was a configuration error.
Hi @jorgecasar could you please share your solution? I'm in the same situation

**Comment by kikar** [comment]
> It was a configuration error.

Hi @jorgecasar could you please share your solution? I'm in the same situation
