### ISSUE TITLE
`@changesets/cli` broken with `"type": "module"` package

### ISSUE THREAD

**Issue by jpzwarte** [changesets/changesets#1149]
If you have a `package.json` with `"type": "module"` then you *should* be able to have `.changeset/changelog-format.js` and use  `import { getInfo, getInfoFromPullRequest } from '@changesets/get-github-info';`.

However, this is broken atm. When you run `yarn changeset`, it will look at the `"bin"` field in `@changesets/cli/package.json` which points to `bin.js`, which in turn contains `require("./");` This causes `dist/cli.cjs.js` to run etc. So the ESM version is never executed.

I'm not familiar enough with "bin" in `package.json` to tell you how to fix this :/

**Comment by jpzwarte** [comment]
Never mind, I had the wrong filename in `config.json` :(

**Comment by younho9** [comment]
Is this issue resolved? I am experiencing the same problem.
