### ISSUE TITLE
Cannot read properties of undefined (reading 'packageJson')

### ISSUE THREAD

**Issue by Yakiyo** [changesets/changesets#1170]
## Affected Packages
pkg:@changesets/cli v2.26.1

## Problem
Running `changeset add` throws this error.
Ive been trying to use it in my repo [here](https://github.com/Yakiyo/dsm). Its a rust based project but i think changeset should work with it too. I'm using pnpm as a package manager but ive tried with npm and yarn too. Both approach failed. 
My `.changeset/config.json`
```json
{
  "$schema": "https://unpkg.com/@changesets/config@2.3.0/schema.json",
  "changelog": "@changesets/cli/changelog",
  "commit": false,
  "fixed": [],
  "linked": [],
  "access": "restricted",
  "baseBranch": "main",
  "updateInternalDependencies": "patch",
  "ignore": []
}
```
Its a single package repo, not a mono repo. Im on windows but ive also tried on a linux container in github codespaces. Not sure what exactly is going wrong.

![image](https://github.com/changesets/changesets/assets/91675932/2693f052-5692-4490-9255-0cdc40529509)

**Comment by Yakiyo** [comment]
any help?

**Comment by Yakiyo** [comment]
I've found the issue. The error is thrown when package.json doesn't contain a version property. Ik its weird to not have a version prop, but i was using it a rust-based project where i only needed node to run some tests, as such i didnt keep a version prop. Maybe the error message could be made a bit more detailed? The current one doesn't really clarify anything

**Comment by marktoman** [comment]
Still the same error on 2.26.2. The message should be more explicit, if nothing else.

**Comment by gethari** [comment]
I faced this issue today, and looks like I accidentally messed up the `pnpm-workspace.yml` file and this was throwing this error on monorepo, just thought of posting here for future if anyone else
