### ISSUE TITLE
Types in `@changesets/types` not properly exposed for import/export

### ISSUE THREAD

**Issue by nicklemmon** [changesets/changesets#1180]
## Affected Packages

`@changesets/types`

## Problem

`@changesets/types` is not properly exporting available types, resulting in a "Cannot find module or corresponding type declarations" TypeScript error.

[CodeSandbox reproduction here](https://codesandbox.io/s/confident-wescoff-5ffsmd?file=/src/index.ts)

## Proposed solution

The `package.json` should not have `"main"` and `"module"` set to empty `.js` files with no type definitions. It looks like `src/index.ts` would be a better target.

**Comment by Andarist** [comment]
It works with just any TS version (with older ones you might not be able to use `import type` syntax but still). See [this TS 3.3 playground](https://www.typescriptlang.org/play?ts=3.3.3#code/JYWwDg9gTgLgBAbzgJQKYBtUEMDOqAK6WAdnAL5wBmUEIcARAAIDGAFiQOap4w4D0MAJ5hu9ANwAoCUJFwAgnAC8KDNjyESAbXpgoqAMowsMVPQC6EoA)
