### ISSUE TITLE
Tries to do a Major version bump instead of a Patch

### ISSUE THREAD

**Issue by Bas950** [changesets/changesets#1182]
## Affected Packages

pkg:changeset
pkg:changelog-github

## Problem

![image](https://github.com/changesets/changesets/assets/34792838/6c277da7-0b2d-4ebc-a9b5-4f5d18168d1c)
As you can see other packages are getting patch bumped but UI is getting a major bump?
I have had it in the following prs:
- https://github.com/PostgreSQL-Typed/PostgreSQL-Typed/pull/47 (from screenshot)
- https://github.com/PostgreSQL-Typed/PostgreSQL-Typed/pull/46 (manually fixed it)

## Proposed solution

It should only patch bump, as there was only a dependency bump.

**Comment by kayhhh** [comment]
also getting this after upgrading @changesets/cli from `2.26.1` to `2.26.2`

**Comment by kayhhh** [comment]
looks like this is intentional behavior? more info about it here https://github.com/changesets/changesets/issues/1011

**Comment by Bas950** [comment]
Closed, I guess it's a copy of https://github.com/changesets/changesets/issues/1011
