### ISSUE TITLE
Support npm OTP/2FA codes

### ISSUE THREAD

**Issue by jesstelford** [changesets/changesets#12]
The `build-releases publish` command will currently fail if an OTP isn't provided via the environment:

```
NPM_CONFIG_OTP=123456 build-releases publish
```

It would be great to get support for prompting the user to enter a OTP if the failure occurs, much like `np` do:

https://github.com/sindresorhus/np/blob/a02e1695603a2a7c34f939d1993c5b1ec4e70e23/source/npm/handle-npm-error.js#L16-L23

**Comment by Noviny** [comment]
Currently publishing is handled by bolt, and changesets doesn't get back detailed enough errors to handle this. Going to be pulling this logic into changesets to resolve #4, so will tackle this after that is done.

**Comment by Noviny** [comment]
Looking at this now. Would appreciate opinions on whether this should hang forever waiting for an OTP, or fail after a time-out. Mostly thinking about releasing through CI hanging in weird ways instead of failing with the obvious npm error message.

**Comment by mitchellhamilton** [comment]
Closed via #106
