### ISSUE TITLE
`pkg:changeset-cli` `changeset status --since=main` not detecting new changesets in PR

### ISSUE THREAD

**Issue by ceng-p** [changesets/changesets#1251]
## Problem
In main there is a (unconsumed) changeset, when I create a pull request with a new changeset the CI runs `npx changeset status --since=main`. it doesn't detect the new changeset.

![image](https://github.com/changesets/changesets/assets/27136738/73e6eb2c-00e2-4429-85a3-34b1be39fdeb)
![image](https://github.com/changesets/changesets/assets/27136738/4dbb720c-b6ca-4bb8-a40b-22b357e74398)

The "lazy-dodos-deny.md" is a result of a rebase on main and the new "spicy-crabs-sip.md" is the new changeset. I would expect that the `status` command would find the new changeset. Have I misunderstood something?

my config.json
```
{
  "$schema": "https://unpkg.com/@changesets/config@2.3.1/schema.json",
  "changelog": "@changesets/cli/changelog",
  "commit": true,
  "fixed": [],
  "linked": [],
  "access": "restricted",
  "baseBranch": "origin/main",
  "updateInternalDependencies": "patch",
  "ignore": []
}
```
## Proposed solution

TBD

**Comment by erikburt** [comment]
I'm pretty sure the `status` command only looks at tracked files. So you would need to commit the new changeset file.
