### ISSUE TITLE
`pkg:cli` missing `./bin.js` in exports

### ISSUE THREAD

**Issue by ludovicm67** [changesets/changesets#1266]
## Affected Packages

- `pkg:cli`

## Problem

I'm getting this error in GitHub Actions after upgrading `@changesets/cli` to `2.27.0`:

```
Error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin.js' is not defined by "exports" in /home/runner/work/***/***/node_modules/@changesets/cli/package.json
Error: Package subpath './bin.js' is not defined by "exports" in /home/runner/work/***/***/node_modules/@changesets/cli/package.json
```

This is when `changeset tag` is called.

## Proposed solution

Add `./bin.js` in the exports in the `package.json` file.

**Comment by alvesvaren** [comment]
I get the same error

**Comment by Andarist** [comment]
Thanks for the info - I located the problem to be located [here](https://github.com/changesets/action/blob/2bb9bcbd6bf4996a55ce459a630a0aa699457f59/src/run.ts#L338).

**Comment by ludovicm67** [comment]
Great, thanks for the quick fix! 👍
