### ISSUE TITLE
Cn not initialize changeset in my project it throws me an error

### ISSUE THREAD

**Issue by CrispenGari** [changesets/changesets#1295]
### Problem
I have intsalled `changesets` using:

```shell
yarn add yarn add @changesets/cli
```

Now when i try to run the command:

```shell
yarn changeset init
```

I am getting an error saying:

```shell
onst stripAnsi = require("strip-ansi")
                  ^
Error [ERR_REQUIRE_ESM]: require() of ES Module .....
```
I'm using Windows 10:

- **Node.js v18.17.1**
- **changesets/cli "^2.27.1**

**Comment by trinhthinh388** [comment]
Same issue here

**Comment by Andarist** [comment]
COuld you check `yarn why strip-ansi` before applying your `resolutions`?

**Comment by taphill** [comment]
I also ran into this error with `@changesets/cli v2.27.1` and `node v20.10.0` on a brand new project

Adding the the resolution that @trinhthinh388 suggested to my package.json file resolved the issue.

**Comment by trinhthinh388** [comment]
> COuld you check `yarn why strip-ansi` before applying your `resolutions`?

Unfortunately, I cannot reproduce after I removed the `resolutions` from my `package.json`, even I removed the `yarn.lock`
