### ISSUE TITLE
changelog Formatter in typescript don't work as expected

### ISSUE THREAD

**Issue by fauxbytes** [changesets/changesets#1323]
Following [this doc](https://github.com/changesets/changesets/blob/main/docs/modifying-changelog-format.md#writing-changelog-formatting-functions), I attempted to implement a changeset formatter:

config,json:
```json
{
  "$schema": "https://unpkg.com/@changesets/config@3.0.0/schema.json",
  "changelog": "./changelog-formatter.ts",
  "commit": false,
  "access": "restricted",
  "baseBranch": "master"
}
```

changelog-formatter.ts:
```ts
import orig from "@changesets/changelog-git";
import { ChangelogFunctions, NewChangesetWithCommit, VersionType } from "@changesets/types";

/**
 * override default formatting: mostly same as default, but with getReleaseLine() excluding commit SHAs 
 */
const defaultChangelogFunctions: ChangelogFunctions = {
    getReleaseLine: async (changeset: NewChangesetWithCommit, _type: VersionType) => {
        const [firstLine, ...futureLines] = changeset.summary.split("\n").map((l) => l.trimEnd());
        return `- ${firstLine}` + (futureLines.length > 0 ? `\n${futureLines.map((l) => `  ${l}`).join("\n")}` : "");
    },
    getDependencyReleaseLine: async (...args) => orig.getDependencyReleaseLine(...args),
};

export default defaultChangelogFunctions;
```

```bash
$ npx changeset version
🦋  error #####\.changeset\changelog-formatter.ts:1
🦋  error import orig from "@changesets/changelog-git";
🦋  error ^^^^^^
🦋  error
🦋  error SyntaxError: Cannot use import statement outside a module
🦋  error     at internalCompileFunction (node:internal/vm:73:18)
🦋  error     at wrapSafe (node:internal/modules/cjs/loader:1176:20)
🦋  error     at Module._compile (node:internal/modules/cjs/loader:1218:27)
🦋  error     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
🦋  error     at Module.load (node:internal/modules/cjs/loader:1117:32)
🦋  error     at Module._load (node:internal/modules/cjs/loader:958:12)
🦋  error     at Module.require (node:internal/modules/cjs/loader:1141:19)
🦋  error     at require (node:internal/modules/cjs/helpers:110:18)
🦋  error     at getNewChangelogEntry (#####\node_modules\@changesets\apply-release-plan\dist\changesets-apply-release-plan.cjs.js:372:31)
🦋  error     at Object.applyReleasePlan [as default] (#####\node_modules\@changesets\apply-release-plan\dist\changesets-apply-release-plan.cjs.js:280:37)
```
Possibly, there's more required to put together an working typescript formatter? A working sample would go a long way.
Thanks,

**Comment by Jintus** [comment]
I'm agree, a working exemple could be very interesting

**Comment by wardxela** [comment]
Same problem. It's a pretty common issue with **TypeScript**. Looks like we can't do pretty much with that at the moment.
If you still want autocomplete for these functions in your editor, current workaround is to use regular JavaScript with **JSDocs**:
```js
/** @type {import('@changesets/types').GetDependencyReleaseLine} */
async function getReleaseLine() {
  return 'Hello world'
}
 
/** @type {import('@changesets/types').GetDependencyReleaseLine} */
async function getDependencyReleaseLine() {
  return 'Hello world
}

module.exports = {
  getReleaseLine,
  getDependencyReleaseLine,
}
```

**Comment by Andarist** [comment]
You could also proxy your TS formatted through a file like this:
```ts
require("tsx/cjs");
require("./changelog-formatter.ts");
```

We don't intend to handle TS files for you, we are not in the business of transpiling source code.

**Comment by fauxbytes** [comment]
> We don't intend to handle TS files for you, we are not in the business of transpiling source code.

bit harsh. 
This issue references the project's documentation (presented in typescript, I believe), and is asking for a working sample. That, together with a generally-lower level of friction, will promote adoption & usage for `changesets` - which I'd think _is_ your business.

**Comment by Andarist** [comment]
This was just a figure of speech. I don't want to engage with transpiling from TS to JS because that would complicate our code. There are multiple available tools that already do this. Should we use Babel? SWC? Esbuild? TS itself? In what versions? We'd increase the install size of this package beyond what is needed.

I'm glad that people enjoy Changesets. I have started to help out maintaining it because I liked the tool. That said, I don't necessarily care how many people use this tool. I don't get anything in return for maintaining it and I'm just doing some free work maintaining it. So transpiling TS to JS here would just add more stuff onto my plate and expose me to a lot of compatibility issues that could arise from this. 

> This issue references the project's documentation (presented in typescript, I believe)

I'd gladly accept PR with docs improvements
