### ISSUE TITLE
Failing at basic multirepo use

### ISSUE THREAD

**Issue by martypdx** [changesets/changesets#1335]
Trying to add changesets in a [pnpm monorepo](https://github.com/azothjs/azoth). I did:

```sh
> pnpm add -D @changesets/cli
> pnpm changesets init
> pnpm changesets
```

But it only wants to publish the root package.json (which is just the monrepo root, not a package), which is set to `private: true`.

Everything suggests changesets is meant to thrive in multi-package repos. So what I am I missing?

**Comment by altano** [comment]
You probably have a version in your package.json. changesets will try to version anything with a version, even private packages, unless you set the `"privatePackages": false` option in your config.json, which would cause it to ignore private packages regardless of the presence of a version.

**Comment by martypdx** [comment]
@altano trying any of those options causes this error:

```zsh
📂 azoth 🚀 pnpm changeset
🦋  error TypeError: Cannot read properties of undefined (reading 'packageJson')
🦋  error     at createChangeset (/Users/marty/dev/azothjs/azoth/node_modules/.pnpm/@changesets+cli@2.27.1/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:392:75)
🦋  error     at add (/Users/marty/dev/azothjs/azoth/node_modules/.pnpm/@changesets+cli@2.27.1/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:506:26)
🦋  error     at async run (/Users/marty/dev/azothjs/azoth/node_modules/.pnpm/@changesets+cli@2.27.1/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1304:5)
📂 azoth 🚀 pnpm changeset
🦋  error TypeError: Cannot read properties of undefined (reading 'packageJson')
🦋  error     at createChangeset (/Users/marty/dev/azothjs/azoth/node_modules/.pnpm/@changesets+cli@2.27.1/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:392:75)
🦋  error     at add (/Users/marty/dev/azothjs/azoth/node_modules/.pnpm/@changesets+cli@2.27.1/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:506:26)
🦋  error     at async run (/Users/marty/dev/azothjs/azoth/node_modules/.pnpm/@changesets+cli@2.27.1/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1304:5)
```

I spent a little time debugging, but it goes through a lot of node/babel polyfill code and is hard to do so from the dist module. But it looks like it is only finding one package initially, then failing when it gets [here](https://github.com/changesets/changesets/blob/0bf89b3709e3e3df6ed5dbb8ece0fb000a55d5f4/packages/cli/src/commands/add/createChangeset.ts#L223).

**Comment by altano** [comment]
@martypdx if you post a repro on stackblitz I’ll try to help.

**Comment by bluwy** [comment]
I'll close this based on the last comment's error, which is tracked at https://github.com/changesets/changesets/issues/841
