### ISSUE TITLE
pnpm v9 and @changesets/cli problem

### ISSUE THREAD

**Issue by shinokada** [changesets/changesets#1343]
## Affected Packages

`pkg:@changesets/cli`

## Problem

When I install `@changesets/cli` on svelte@5.0.0-next.108 using pnpm v9, I get the following issues with peer dependencies:

```
├─┬ vite 5.2.9
│ └── ✕ unmet peer @types/node@"^18.0.0 || >=20.0.0": found 12.20.55
└─┬ vitest 1.5.0
  └── ✕ unmet peer @types/node@"^18.0.0 || >=20.0.0": found 12.20.55
```

1. If I change to pnpm v8, I don't have any problems.
2. If I remove `@changesets/cli`, the problem disappears.

## Proposed solution

Make compatible with `pnpm` v9.

**Comment by R-Bower** [comment]
What version of node are you using?

**Comment by shinokada** [comment]
Using pnpm 9.1.3 solved the problem. Thanks.
