### ISSUE TITLE
Error: error log.http is not a function

### ISSUE THREAD

**Issue by igoldny** [changesets/changesets#1353]
## Affected Packages

@changesets/cli

## Problem

We recently started seeing frequent failures on npm info.
They appear on random packages in our CI with the following error:
```
🦋  error Received an unknown error code: null for npm info "@my-package-name"
🦋  error log.http is not a function
```
running `npm info` on those packages locally and on CI works.
i wonder if the error `error log.http is not a function` means something?

**Comment by Andarist** [comment]
We don't use any such function - so I'm not sure where this error comes from. Perhaps this is returned directly from the npm's API (or the CLI?). You'd have to do some deeper debugging to get to the bottom of this.

**Comment by sashuk** [comment]
@igoldny I observe the same, leaving comment for activity

**Comment by sashuk** [comment]
@igoldny Can you please try updating to the latest `@changesets/*` versions?

**Comment by igoldny** [comment]
yes @sashuk it seems to be it,
I found that some other unrelated affecting [spawndamnit](https://github.com/jamiebuilds/spawndamnit) package by overwriting some global it depending on, had to go over the update deps I did one by one to track the right change.
I will give it a shot, thanks

**Comment by Andarist** [comment]
Thanks for the update. Since it isn't actionable on our side I'm closing this issue

**Comment by sashuk** [comment]
> I found that some other unrelated dep affecting

@igoldny Can you please elaborate what was the dependency and what it overrides?
