### ISSUE TITLE
Error:  Failed to find where HEAD diverged from undefined. Does undefined exist?

### ISSUE THREAD

**Issue by karol-f** [changesets/changesets#1356]
## Problem with `@changesets/cli@2.27.2`.

Newly introduced version `2.27.2` causes problems with the same setup as before (even after a clean NPM install with removed lock file and node_modules folder):

```
> changeset status --verbose
🦋  error Error: Failed to find where HEAD diverged from undefined. Does undefined exist?
🦋  error     at getDivergedCommit (/builds/.../node_modules/@changesets/git/dist/changesets-git.cjs.js:66:11)
🦋  error     at async getChangedFilesSince (/builds/.../node_modules/@changesets/git/dist/changesets-git.cjs.js:198:22)
```

## Problem

Newly introduced version `2.27.2` causes problems with the same setup as before (even after a clean NPM install with removed lock file and node_modules folder). 
Version up to 2.27.1 works fine.

**Comment by AkatQuas** [comment]
2.27.1 is good . 😅

**Comment by Sec-ant** [comment]
Same, here is the workflow step that shows the error: https://github.com/Sec-ant/zxing-wasm/actions/runs/9153151340/job/25161639566#step:4:10
