### ISSUE TITLE
How to specify folder to publish in single package

### ISSUE THREAD

**Issue by Algrus8** [changesets/changesets#1365]
## Affected Packages
Single package

## Problem
I am unable to understand how to specify the directory for publishing the package. I found this issue: https://github.com/changesets/changesets/pull/428, but I couldn't find any documentation related to it.
My build in ".publish" folder

**Comment by bluwy** [comment]
In that PR linked, it mentions the docs at https://www.npmjs.com/package/@lerna/publish#publishconfigdirectory

It looks non-standard, but you'd configure it like this:

```json
{
  "name": "my-pkg",
  "publishConfig": {
    "directory": ".publish"
  }
}
```

**Comment by bluwy** [comment]
Related: https://github.com/changesets/changesets/issues/733
