### ISSUE TITLE
Bug with Bun

### ISSUE THREAD

**Issue by migueldamota** [changesets/changesets#1376]
## Affected Packages

I don't know which package replaces workspace packages versions

## Problem

Hi there. I recently updated my codebase to bun and published my private packages. However, I recently noticed that if I have a workspace dependency defined for a package (`"package-a": "workspace:*"`) the version doesn't get updated and it stays at `"workspace:*"` on publish, so if I try to install it I get this error:

```
In : "package-a@workspace:*" is in the dependencies but no package named "package-a" is present in the workspace
```

Hopefully you know what I mean, if not don't hesitate to ask 😊

## Proposed solution

I don't know if this is changeset related or a problem with bun

**Comment by Andarist** [comment]
For the time being, you should use `bun` to publish your packages. Please configure `changesets/action` with your custom `publish` script that will call `bun publish-command-i-dont-know-how-to-use-bun && changeset tag`.

**Comment by Nickersoft** [comment]
@migueldamota I'm curious, how did you end up publishing? Bun doesn't have a `publish` command yet, and `npm` doesn't support the `workspace:*` protocol AFAIK. I'm using PNPM to publish right now 😂

**Comment by migueldamota** [comment]
Hi @Nickersoft. I am using a library called [bunpublish](https://github.com/morlay/bunpublish). Be sure to also add a `bunfig.toml` to your project like this:

```toml
[install]
registry = { url = "https://registry.npmjs.org", token = "$NPM_TOKEN" }
```

Then I just added bunpublish to my `ci:publish` script and then it got published just fine. 

```json
"scripts": {
  "ci:publish": "bunpublish && changeset tag"
}
```
