### ISSUE TITLE
TypeError: Cannot destructure property 'packageJson' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by sammaji** [changesets/changesets#1403]
## Problem
Running `npx changeset version` causes `TypeError: Cannot destructure property 'packageJson' of 'undefined' as it is undefined.`

**Comment by sammaji** [comment]
Closing this as issue as fixed.

I copies the .changeset folder from another project and forgot to update the package name.

**Comment by oshytiko** [comment]
I would argue that the the issue should be re-opened.

I have wasted hours on debugging issue. The error should be added, like these are unrelated changes, I'm aborting until you fix these.

**Comment by benmccann** [comment]
I've hit this as well. Here's a stack trace:

> 🦋  error TypeError: Cannot destructure property 'packageJson' of 'undefined' as it is undefined.
🦋  error     at Object.shouldSkipPackage (/home/runner/work/svelte-add/svelte-add/node_modules/.pnpm/@changesets+should-skip-package@0.1.0/node_modules/@changesets/should-skip-package/dist/changesets-should-skip-package.cjs.js:6:3)
🦋  error     at getRelevantChangesets (/home/runner/work/svelte-add/svelte-add/node_modules/.pnpm/@changesets+assemble-release-plan@6.0.2/node_modules/@changesets/assemble-release-plan/dist/changesets-assemble-release-plan.cjs.js:560:29)
🦋  error     at Object.assembleReleasePlan [as default] (/home/runner/work/svelte-add/svelte-add/node_modules/.pnpm/@changesets+assemble-release-plan@6.0.2/node_modules/@changesets/assemble-release-plan/dist/changesets-assemble-release-plan.cjs.js:488:30)
🦋  error     at version (/home/runner/work/svelte-add/svelte-add/node_modules/.pnpm/@changesets+cli@2.27.6/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1[23](https://github.com/svelte-add/svelte-add/actions/runs/10062499576/job/27815275543#step:8:24)1:60)
🦋  error     at async run (/home/runner/work/svelte-add/svelte-add/node_modules/.pnpm/@changesets+cli@2.27.6/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1413:11)

**Comment by manuel3108** [comment]
> I've hit this as well. Here's a stack trace:
> 
> > 🦋  error TypeError: Cannot destructure property 'packageJson' of 'undefined' as it is undefined.
> > 🦋  error     at Object.shouldSkipPackage (/home/runner/work/svelte-add/svelte-add/node_modules/.pnpm/@changesets+should-skip-package@0.1.0/node_modules/@changesets/should-skip-package/dist/changesets-should-skip-package.cjs.js:6:3)
> > 🦋  error     at getRelevantChangesets (/home/runner/work/svelte-add/svelte-add/node_modules/.pnpm/@changesets+assemble-release-plan@6.0.2/node_modules/@changesets/assemble-release-plan/dist/changesets-assemble-release-plan.cjs.js:560:29)
> > 🦋  error     at Object.assembleReleasePlan [as default] (/home/runner/work/svelte-add/svelte-add/node_modules/.pnpm/@changesets+assemble-release-plan@6.0.2/node_modules/@changesets/assemble-release-plan/dist/changesets-assemble-release-plan.cjs.js:488:30)
> > 🦋  error     at version (/home/runner/work/svelte-add/svelte-add/node_modules/.pnpm/@changesets+cli@2.27.6/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1[23](https://github.com/svelte-add/svelte-add/actions/runs/10062499576/job/27815275543#step:8:24)1:60)
> > 🦋  error     at async run (/home/runner/work/svelte-add/svelte-add/node_modules/.pnpm/@changesets+cli@2.27.6/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1413:11)

To add some more context, this happend because we were trying to add changeset for a package that no longer existed (was coming from some old PR).

Adjusting the scope of that changset fixed it.

**Comment by higherorderfunctor** [comment]
Created a patch.  Have not gone through changesets code base to see if other types of errors might throw, so the message may not be accurate enough to upstream in its current state, but I can at least zero in now on what is failing.

```
 export MAIN_SHA=$(git ls-remote origin refs/heads/main | awk '{print $1}')
 pnpm changeset status --since $MAIN_SHA
🦋  error Error: Failed to locate package for changeset: `<my missing package>` in '<changeset name>'
     ... <stacktrace>
```

```diff
diff --git a/dist/changesets-assemble-release-plan.cjs.js b/dist/changesets-assemble-release-plan.cjs.js
index 4f7b5e5b37bb05874a5c1d8e583e29d4a9593ecf..ddf1b40695633eebc92b6c06b458a865390fa868 100644
--- a/dist/changesets-assemble-release-plan.cjs.js
+++ b/dist/changesets-assemble-release-plan.cjs.js
@@ -605,13 +605,17 @@ function getRelevantChangesets(changesets, packagesByName, config, preState) {
     const notSkippedPackages = [];
 
     for (const release of changeset.releases) {
-      if (shouldSkipPackage.shouldSkipPackage(packagesByName.get(release.name), {
-        ignore: config.ignore,
-        allowPrivatePackages: config.privatePackages.version
-      })) {
-        skippedPackages.push(release.name);
-      } else {
-        notSkippedPackages.push(release.name);
+      try {
+        if (shouldSkipPackage.shouldSkipPackage(packagesByName.get(release.name), {
+          ignore: config.ignore,
+          allowPrivatePackages: config.privatePackages.version
+        })) {
+          skippedPackages.push(release.name);
+        } else {
+          notSkippedPackages.push(release.name);
+        }
+      } catch (cause) {
+        throw new Error(`Failed to locate package for changeset: \`${release.name}\` in '${changeset.id}'`, { cause });
       }
     }
```
