### ISSUE TITLE
Replace `chalk` dependency with a lighter alternative

### ISSUE THREAD

**Issue by trivikr** [changesets/changesets#1414]
## Affected Packages

* `pkg:cli`
* `pkg:get-dependents-graph`
* `pkg:logger`
* `pkg:read`

## Problem

Recently, the [Ecosystem Performance](https://e18e.dev/) was formed to cleanup, speedup, levelup the JavaScript Ecosystem.
Socket Security team wrote a blog post about it https://socket.dev/blog/javascript-community-launches-e18e-initiative-to-improve-ecosystem-performance

On the e18e cleanup channel on Discord, multiple solutions are being discussed. One of them is to replace `chalk` with `picocolors`.

I see that changesets uses chalk:
* https://github.com/changesets/changesets/blob/b59375614b1b3dabdf67806cd202defb314686a8/packages/read/package.json#L27
* https://github.com/changesets/changesets/blob/b59375614b1b3dabdf67806cd202defb314686a8/packages/logger/package.json#L22
* https://github.com/changesets/changesets/blob/b59375614b1b3dabdf67806cd202defb314686a8/packages/cli/package.json#L87
* https://github.com/changesets/changesets/blob/b59375614b1b3dabdf67806cd202defb314686a8/packages/get-dependents-graph/package.json#L24

## Proposed solution

Replace `chalk` with a lighter alternative, like `picocolors`.

**Comment by Andarist** [comment]
We can consider a PR implementing this change. Ideally, a PR wouldn't change the minimal supported node version of Changesets

**Comment by trivikr** [comment]
> We can consider a PR implementing this change

Posted at https://github.com/changesets/changesets/pull/1417

> Ideally, a PR wouldn't change the minimal supported node version of Changesets.

It doesn't.
* `changeset` supports Node.js 14+
* `picocolors@1.x` supports Node.js 6+
