### ISSUE TITLE
Is `--version` flag no longer supported?

### ISSUE THREAD

**Issue by cometkim** [changesets/changesets#1418]
I was using code to check the exact version of an installed changeset CLI with `changeset --version`.

I'm not sure if there was an announcement, but I just noticed that its behavior changed to be same as `changeset version` and broke my workflow.

Is that an intended change or a bug?

**Comment by Andarist** [comment]
my guess is that it was accidentally broken by https://github.com/changesets/changesets/pull/1392 , cc @bluwy
