### ISSUE TITLE
`.npmignore` is not being honored

### ISSUE THREAD

**Issue by somewhatabstract** [changesets/changesets#1447]
## Affected Packages

CLI

## Problem

We have some repos where we use changesets. It's awesome. However, we added an `.npmignore` file to ignore some things that were getting packaged. Using `npm pack --dry-run` on each package shows that it properly excludes the things that are in the `.npmignore` file, but when we publish with `changesets publish`, they are still included.

I have checked and we aren't using the `files` property in the package.json for each package.

## Proposed solution

Have `changesets publish` honor the ignore file.

**Comment by Andarist** [comment]
where is your `.npmignore` located? Under the hood we delegate to npm/pnpm to do packing and publishing so it’s not a lot we can do about it. It’s possible that we spawn those in wrong cwd or smth though

**Comment by somewhatabstract** [comment]
The `.npmignore` is at the root of the repo.

You can see my PR where I added it [here][1]. The PR includes my workaround which is a script to delete files that are matched by `.npmignore` and `.gitignore` (added that last bit so if we run this locally, we don't delete change-controlled files - not ideal, just working on a low maintenance middle ground).

[1]:https://github.com/Khan/wonder-blocks/pull/2312

**Comment by Andarist** [comment]
It would be great if you could instrument this to see what exact options/flags are passed to `npm` by us:
https://github.com/changesets/changesets/blob/5150fc174ea55406da401cacdd68a9a2e754126d/packages/cli/src/commands/publish/npm-utils.ts#L191-L197

then we could compare those with what you are doing manually. I didn't even know that you could use monorepo-wide `.npmignore`

**Comment by somewhatabstract** [comment]
Well, thanks for that suggestion. It made me realize (and I should've know this) that we're publishing with `yarn` and there's a known issue with how `yarn` handles all this. So, it's not a changeset issue at all 🤦🏻.

I have a workaround that helps, but there's nothing y'all need to do. Thanks for taking a look. I'll close this out.

**Comment by Andarist** [comment]
If you are using `changeset publish` then that won't call into `yarn publish` (which is a long-standing issue) - it keeps using `npm publish` in such a case.

**Comment by somewhatabstract** [comment]
Oh interesting, perhaps it is a changeset issue still then. However, I've decided to use the `files` property in each package.json instead since that feels like a better way to handle this longterm. I can reopen this ticket if you would like though, and gather that instrumentation for you anyway.
