### ISSUE TITLE
Run prettier on changesets, changelogs and the changeset config if there is a prettier config in the project

### ISSUE THREAD

**Issue by mitchellhamilton** [changesets/changesets#20]
I've noticed that often someone adds a changeset in one PR and then after that PR is merged but before the next release, someone submits another PR which adds a newline to the changeset md file because they opened it their editor and it auto formatted or they ran prettier and it formatted the file. This is kind of annoying from a PR reviewing perspective because they're just a random  and I think the changesets tool is in a good position to fix the problem. 

So this is the behavior that I think would be nice: 
Only do these things if there's a prettier config in the repo (or maybe check whatever heuristic jest uses and do that)
- When creating the `.changeset/config.js` run prettier over the file when it's written
- Run prettier on changesets when they're written. My thought is that prettier should definitely be run on the markdown, not so sure about the json.
- Run prettier against changelogs when changesets are consumed

One argument against this might be that "caring about prettier is a pretty opinionated thing for a tool that does versioning" but there's already precedence with jest as an example using prettier for `toMatchInlineSnapshot`.

> this might be a bad idea and the problem might not be big enough to justify caring about prettier.

**Comment by Noviny** [comment]
I think this is pretty reasonable to do. I was doing it for something else I was doing as code generation, but can't remember what it was.

NB: I think you would prettier new text, not the entire file, which might make different results. The difference is between:

```
fs.writeFile(prettier(someContents))
```

and

```
fs.writeFile(someContents)
prettierCall(filePath)
```

Except with correct syntaxes.

Any opinions? The first might not solve adding an extra line at the end of file.

**Comment by mitchellhamilton** [comment]
I feel like running prettier on the entire file would be better because I think that changesets should do exactly what the project's prettier config says and when you run prettier normally, it's on the whole file contents, not just a part of it so if you then ran prettier because of an editor format on save thing, the contents has the potential to change which would defeat a large part of the point of changsets running prettier.

**Comment by Noviny** [comment]
I guess my biggest concern with this is when people don't run prettier on their `.md` files, we'll begin tampering with how their files are formatted if prettier is installed. Maybe if it's on by default (using the user's prettier settings) but has a config option to switch it off?

**Comment by Noviny** [comment]
NOPE - gonna say changelogs must be pretty. (You can add a prettier config and turn prettier off for filetypes to disable I think)

**Comment by Noviny** [comment]
Oh, and this is merged.
