### ISSUE TITLE
configure commit message

### ISSUE THREAD

**Issue by unional** [changesets/changesets#246]
## Problem

When `changesets` commit, it uses the message 'Version Packages':

```sh
git commit -m Version Packages
```

This fails when the repository is configured with commit lint.

Here is one example:
https://github.com/unional/standard-log/commit/bc0bc71e5cd33c37abf6f5341cd90531795a84e8/checks?check_suite_id=389611134

## Proposed solution

Make the commit message configurable.

**Comment by jmcdo29** [comment]
Is there anything that can be done to help this? I realize it may be difficult to allow for advanced configurations like `chore: bump <packageName>@<version>`, but at least allowing the addition of of a prefix could be useful for things like commitlint

**Comment by JounQin** [comment]
+1 for this, we're using `commitlint` too, we have to disable git hooks for `commit-msg` on CI.

**Comment by JounQin** [comment]
I found it can be configured in GitHub Action by [inputs](https://github.com/changesets/action#inputs) `commit` and `title`.

```yml
commit: 'chore: release package(s)'
title: 'chore: release package(s)'
```

**Comment by unional** [comment]
It can now be done using the `title` field in the config:

```jsonc
// .changeset/config.json
{
  "title": "..."
}
```
