### ISSUE TITLE
Choosing all packages to bump also includes ignored packages and results in error during version phase

### ISSUE THREAD

**Issue by dotansimha** [changesets/changesets#436]
## Affected Packages

- not sure, guess cli

## Problem

I tried to create a changeset using `yarn chageset`. I needed to bump all packages in your monorepo. So I choose `all changes package` and `all unchanged packages`. It results in adding ignored packages (defined in `ignore` in the config files) to the list of changes. 

When trying to run `yarn changesets version` command, it now thrown an errors:

```
Mixed changesets that contain both ignored and not ignored packages are not allowed
```

## Proposed solution

Remove ignored packages from the selection list in `yarn changeset` command? 🤔

**Comment by Andarist** [comment]
Good suggestion - we probably should filter out any dependants of ignored packages as IIRC we don't allow them to be published because it would possibly result in a broken release.
