### ISSUE TITLE
Change how we ask questions

### ISSUE THREAD

**Issue by Noviny** [changesets/changesets#52]
Currently we ask question as:

```
1. Select packages to update: [list of all packages]
=>
2. Select bump type for package [patch, minor, major]
=>
Repeat step two for each package
```

This means that the number of questions you have to think about is 1 + packages-bumped, and scales up with larger system changes.

Proposed new format is:

```
1. Select packages to update: [list of all packages]
=>
2. Which of these packages are a major change? [list of selected packages]
=>
3. Which of these packages are a minor change? [list of selected packages - major changed packages)
=>
4. The rest (list them) will be a minor change - is this okay?
```

This reduces the questions to always 4.

---

Other concerns:

**This makes it too easy to mass-update**
We previously removed a bunch of questions because while being the most correct in querying individual information is good, decision overloading users gets worse results than being a bit smarter.

**If I am updating less than three packages, I will get asked more questions**
We could theoretically avoid this by switching to the old format for 1 or 2 packages, but I would like to have a consistent predictable experience when updating packages.

**Could we ask one question only?**

If we had one Very Complicated question that looked like:

```
Select the bump type of all packages:
pkgA *none* | patch | minor | major
pkgB *none* | patch | minor | major
```

and could cursor both up+down and left+right, you could just use one set of selects to choose EVERYTHING.

I... don't actually like this. It feels like to get all the answers right you need to hold too much information in your head at once, once again upping the complexity cost of getting your changeset 'right'.

**Comment by mitchellhamilton** [comment]
> I... don't actually like this. It feels like to get all the answers right you need to hold too much information in your head at once, once again upping the complexity cost of getting your changeset 'right'.

I strongly agree.

Another concern:

**How do we ask questions in single-package repos?**

I think the best answer would probably be don't change anything and ask the same question we do right now.

**Comment by Noviny** [comment]
> I strongly agree.

Expanding on this would be good. Is this a vote for option 3 if we can get it working?

**Comment by Noviny** [comment]
Note option 3 makes features such as 'select all' and 'select all changed' harder (though obv not impossible)

**Comment by mitchellhamilton** [comment]
> Expanding on this would be good. Is this a vote for option 3 if we can get it working?

It’s a vote for option 3 being bad because people have to hold too much information in their head at once.

**Comment by mitchellhamilton** [comment]
Speaking of select all and select all changed, I think they should be changed so rather than items in the the select, when you press `a`, all of the items should be selected and `c` should select all the changed items.

**Comment by Noviny** [comment]
*bangs head quietly on keyboard*

Despite quote tweeting it, I read 'I strongly agree' as 'I strongly disagree' like 5 times. 🙏 for asking more about it.

> Speaking of select all and select all changed...

Yeah, this is way better behavior. At the moment, this console manipulation is handed over to `inquirer`, so would need to see if we can add hotkeys to that.

It would be good to be able to `select all`, and then de-select as needed, or `select all changed` then check that meets your expectations.
