### ISSUE TITLE
fix formatting of summary in cli workflow

### ISSUE THREAD

**Issue by ianstormtaylor** [changesets/changesets#560]
## Affected Packages

`pkg:cli`

## Problem

The summarization of a changeset in the CLI is a nice idea, but right now the formatting seems broken:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/311752/113428237-70b8a200-93a4-11eb-9bf4-367e3a460bd3.png">

## Proposed solution

1. I think if you open the editor to write the changeset (instead of doing it directly in the terminal) the summary step should be eliminated. Because you've already just seen the entire changeset file and have saved and closed it.

2. The formatting should be fixed and simplified. Potentially something like this:

```
🦋  === Summary of changeset ===
🦋  minor: slate, slate-react
🦋  patch: slate-history
🦋  
🦋  Note: all dependents of these packages that are incompatible with the new version 
🦋  will be patch bumped when this changeset is applied.
🦋  
🦋  Is this your desired changeset? (Y/n) · true
```

Which includes things like:

- Reduce noise around the "note", using just simply red+bold on the word "Note:" will get the job done, and right now it's so noisey that it makes other pieces hard to read.
- Reduce noise on `major/minor/patch`. Again color will get the job done. (And the formatting I've used mimics how they are formatted in the questions already, which is good.)
- Collapse packages onto a single line since the majority case is have either all in one type (and a long list), or just a few packages changing, so no need to make it verbose.
- Collapse header into a single line, since it was unnecessary to have two before.

**Comment by Andarist** [comment]
> I think if you open the editor to write the changeset (instead of doing it directly in the terminal) the summary step should be eliminated. Because you've already just seen the entire changeset file and have saved and closed it.

https://github.com/atlassian/changesets/pull/562

> Reduce noise around the "note", using just simply red+bold on the word "Note:" will get the job done, and right now it's so noisey that it makes other pieces hard to read.

I've looked into why this box was wrongly formatted - we are using `boxen@^1` which doesn't handle text-wrapping. This has been implemented though so I've wanted to bump this dependency first, but I've been stopped by https://github.com/sindresorhus/boxen/pull/52 . Even if that would get resolved there is still no way (from what I can tell) to "offset" the box by the length of our prefix: https://github.com/sindresorhus/boxen/issues/53 . So either way - I think we should drop this dependency. I also agree with you that this is somewhat noisy.

> Reduce noise on major/minor/patch. Again color will get the job done. (And the formatting I've used mimics how they are formatted in the questions already, which is good.)

As to colors - do you just propose to color major/minor/patch "labels"?

Not sure if I understand the latter part - I mean, not sure exactly how the proposed formatting mimics how packages are formatted in questions. A visual would be helpful for this.

> Collapse packages onto a single line since the majority case is have either all in one type (and a long list), or just a few packages changing, so no need to make it verbose.

Agreed, not completely sure how we should treat major CLI output revamps in relation to semver. I'm inclined to say that we can be liberal about this though.

> Collapse header into a single line, since it was unnecessary to have two before.

+1 on merging "Summary" and "Realising..." headers

**Comment by mitchellhamilton** [comment]
This all sounds good to me.

**Comment by ianstormtaylor** [comment]
> As to colors - do you just propose to color major/minor/patch "labels"?
>
> Not sure if I understand the latter part - I mean, not sure exactly how the proposed formatting mimics how packages are formatted in questions. A visual would be helpful for this.

@Andarist I just meant that currently the two places that display the "minor" concept in that screenshot are using two different types of formatting. (1) is using lowercase, color, bold. (2) is using uppercase, square brackets, non-bold, color. My suggestion is to unify on (1).
