### ISSUE TITLE
Mixed versions across workspaces

### ISSUE THREAD

**Issue by raphaelokon** [changesets/changesets#581]
Hi there.

We are evaluating to replace Lerna with Yarn workspaces + Changesets and need input if the following concept is possible with changesets:

```js
  "workspaces": [
    "libs/*",  // All packages in `libs` should be versioned independenly
    "main/*",  // All packages in `main` should have one fixed/locked versioning
  ]
```

We would ideally have an independent versioning (like all packages can get a custom version) for all packages inside the `libs/` workspace and a fixed version across packages (like in LErna’s fixed/locked mode) under `main/`. 

Is this possible with changesets?
 
Cheers 😊

**Comment by Andarist** [comment]
It's possible - you could use `linked` config option for all packages in the `main` directory. Note that this works slightly in a different way than Lerna's fixed/locked mode but I think that it should suffice for the majority of use cases.

There have been some requests for the "true" fixed/locked mode so we could consider adding support for this somehow but at the moment we don't have manpower to design such a feature.

**Comment by raphaelokon** [comment]
Hi @Andarist 

So grateful for your feedback on this. I already saw the `linked` config option, but the example made me puzzle as how to always force each package inside the `linked` array to update to one and the same version.

> There have been some requests for the "true" fixed/locked mode so we could consider adding support for this somehow but at the moment we don't have manpower to design such a feature.

Sure – we could look into helping out. 

How would you describe the difference between Lerna’s fixed/locked mode and Changesets fixed mode?

Thanks again and have a good one.

**Comment by Andarist** [comment]
> How would you describe the difference between Lerna’s fixed/locked mode and Changesets fixed mode?

If by "Changesets fixed mode" you are referring to our linked mode then:
- if you have a set of linked packages and you publish multiple packages from that set then all of those releases will have the very same version
- but if you only release some subset of packages from that set of linked packages then those packages that don't have to be released won't be released. Whereas with Lerna's fixed mode all packages are always released together, even if some of them have not been touched

**Comment by Andarist** [comment]
The fixed mode is being implemented in https://github.com/changesets/changesets/pull/690 . Please check out if it matches your expectations
