### ISSUE TITLE
Security issues in some dependencies

### ISSUE THREAD

**Issue by timiyay** [changesets/changesets#587]
## Affected Packages

`@changesets/cli`

## Problem

Github is reporting security alerts in our apps that use `@changesets/cli`. The alerts are for

- `hosted-git-info <3.0.8`, which we depend on via `@changesets/cli > meow > normalize-package-data > hosted-git-info` (https://github.com/advisories/GHSA-43f8-2h32-f4cj)
- `mixme <0.5.1`, which we depend on via `@changesets/cli > tty-table > csv > stream-transform > mixme` (https://github.com/advisories/GHSA-79jw-6wg7-r9g4)

## Proposed solution

Both of the top-level packages that `@changesets/cli` depends on are out of date, so maybe a quick bump of each will solve things?

This repo is using `meow@^5.0.0` where the latest is `meow@10.0.0`.

This repo is also using `tty-table@^2.8.10`, where the latest is `tty-table@4.1.3`.

**Comment by timiyay** [comment]
I had a quick go at a bump PR to fix this.

Bumping `tty-table` to latest and running `yarn test` was all good 🟢 

Bumping `meow` was more problematic, and there's some breaking changes that'll require a better understanding of this repo.

Bumping to latest `meow@10` fails the following tests in `packages/release-utils/src/run.test.ts`
```
version › returns the right changed packages and pushes to the remote
version › only includes bumped packages in the returned changed packages
version › doesn't include ignored package that got a dependency update in returned versions
```

They all fail when attempting to `import meow from 'meow'` with:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: changesets/node_modules/meow/index.js
   require() of ES modules is not supported.
   require() of changesets/node_modules/meow/index.js from changesets/packages/cli/src/index.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
   Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from changesets/node_modules/meow/package.json.
```

If I try bumping to `meow@9` or `meow@8` instead, I get 1 failure in ` packages/release-utils/src/run.test.ts` for `version › doesn't include ignored package that got a dependency update in returned versions`

```

    The command "node ./node_modules/@changesets/cli/bin.js version" failed with code 1

    ��  error It looks like you are trying to use the `--ignore` option while ignore is defined in the config file. This is currently not allowed, you can only use one of them at a time.

      105 |   let result = await childProcess;
      106 |   if (!options?.ignoreReturnCode && result.code !== 0) {
    > 107 |     throw new Error(
          |           ^
      108 |       `The command "${command} ${args.join(" ")}" failed with code ${
      109 |         result.code
      110 |       }\n${result.stdout.toString("utf8")}\n${result.stderr.toString("utf8")}`

      at execWithOutput (packages/release-utils/src/utils.ts:107:11)
      at runVersion (packages/release-utils/src/run.ts:133:5)
      at Object.<anonymous> (packages/release-utils/src/run.test.ts:266:31)
```

**Comment by milovangudelj** [comment]
Sorry if this is not the right place for this, but I'm facing a similar security alert.

Apparently `meow v6.0.0` has `trim-newlines v3.0.0` as a dependency which causes this alert to pop up:
`Uncontrolled Resource Consumption in trim-newlines`.

A fix was introduced in `trim-newlines v3.0.1` and meow bumped it's dependency version from `trim-newlines v3.0.0` to `trim-newlines v4.0.0` on [Apr 27, 2021](https://github.com/sindresorhus/meow/commit/8c12b2dd2988d6d358a75c4b3962ab452640eac7) and released it as part of `meow v10.0.0` on [May 5, 2021](https://github.com/sindresorhus/meow/commit/6052e692e4561b157d3a251d0ba045fe34303399).

**Comment by benmccann** [comment]
Hmm. meow 10 is now ESM-only. That means `@changesets/cli` will need to be converted to be ESM-only as well. Alternatively it could be imported with a dynamic import, but I'm not sure how feasible that would be. I would think that dropping the CJS build of `@changesets/cli` shouldn't be a big deal as folks wouldn't generally be importing it as a library. That seems like the best path forward from several respects: it simplifies the distributed package, it makes the distributed package much smaller, it requires the fewest code changes, it's the most future-proofed and forward-looking.

**Comment by jorenbroekema** [comment]
That's not entirely accurate, it just means that `@changesets/cli` _source_ needs to be ESM, but you can still dual-publish a CJS version of it using a build-tool such as esbuild, rollup, etc., you can use package entrypoints to then allow users to import from the right format based on which format they are using to import with (CJS/ESM).

**Comment by benmccann** [comment]
Dual publishing works only if the dependency is bundled. It currently isn't, but I suppose that would be another solution

**Comment by jorenbroekema** [comment]
Yeah I suppose this is how some folks are (whether consciously or not) pressuring the Node ecosystem to ditch CJS:
- more packages become ESM only, since it's the modern format
- forces dependant packages to either become ESM-only or dual publish, bundling the CJS dep into itself as converted ESM
- the latter option creates bigger bundlesizes down the line for many people still using CJS
- incentivises more people to move away from CJS (hopefully)

**Comment by benmccann** [comment]
This issue can be closed as `tty-table` and `meow` have been removed as dependencies
