### ISSUE TITLE
Explore if we can populate github releases using changesets

### ISSUE THREAD

**Issue by Noviny** [changesets/changesets#6]
Explore if we can populate github releases using changesets - either a separate package or a modification on the existing toolset

**Comment by jesstelford** [comment]
Corollary to this is annotating the git tags with the same changeset info, so the info also lives independent of the hosted Git service.

See https://github.com/keystonejs/keystone/issues/795 for some (old) research into this.

**Comment by benmvp** [comment]
Unlikely this'll ever get done given the age of this issue, but I stumbled upon this hoping there was a way to accomplish this

**Comment by Andarist** [comment]
@benmvp could you describe what you are trying to do? [`changesets/action`](https://github.com/changesets/action) can already be used to create GitHub releases

**Comment by benmvp** [comment]
> @benmvp could you describe what you are trying to do? [`changesets/action`](https://github.com/changesets/action) can already be used to create GitHub releases

Ah yes, you're right! Thanks for the quick and helpful response @Andarist! 🙏🏾 

(I guess this issue can be closed?)

**Comment by Andarist** [comment]
Let me know if you have any questions regarding Changesets or if you have any trouble setting it up. My DMs on Twitter are open.
