### ISSUE TITLE
Packages with no version cause exception with prereleases

### ISSUE THREAD

**Issue by justinfagnani** [changesets/changesets#604]
## Affected Packages

assemble-release-plan

## Problem

We have some private utility packages that are included in our Lerna config so that they can depend on other packages. One of these was missing a version field and that caused an exception.

```
🦋  error TypeError: Cannot read property 'prerelease' of null
🦋  error     at getPreVersion (/.../node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:371:27)
🦋  error     at getPreInfo (/.../node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:524:45)
🦋  error     at Object.assembleReleasePlan [as default] (/.../node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:420:19)
🦋  error     at version (/.../node_modules/@changesets/cli/dist/cli.cjs.dev.js:566:60)
🦋  error     at async run$1 (/.../node_modules/@changesets/cli/dist/cli.cjs.dev.js:1210:11)
```

## Proposed solution

It looks like a simple fix here would work:
https://github.com/atlassian/changesets/blob/de2b4a5a7b244a37d94625bcb70ecde9dde5b612/packages/assemble-release-plan/src/index.ts#L14

This could change be null-safe:
```ts
  let preVersion = parsed?.prerelease[1] ?? -1;
```

**Comment by Andarist** [comment]
Thank you for the report - I will definitely take a look at this and provide some kind of a fix. I think we prefer to have a version field, even for private packages - is that a problem for you? But, of course, even if we expect it to exist etc we shouldn't crash like this - so this is still a legitimate issue.

**Comment by justinfagnani** [comment]
Yeah, adding a version was fine, but it took a while to find out what the problem was. A warning would be great.

**Comment by bluwy** [comment]
I'll close this in favour of https://github.com/changesets/changesets/issues/835 since there has been more activity there
