### ISSUE TITLE
Settings of `@changesets/read` are incorrect and cause problems when using native esm

### ISSUE THREAD

**Issue by JounQin** [changesets/changesets#622]
## Affected Packages

pkg:@changesets/read

## Problem

`@changesets/read` is not set as `type: "module"` currently, so `dist/read.cjs.js` will be used in native esm, but [`dist/read.cjs.prod.js`](https://unpkg.com/browse/@changesets/read@0.4.7/dist/read.cjs.prod.js) is still wrapped into `exports.default` statement.

## Proposed solution

Change `dist/read.cjs.js` like following:

```js
'use strict';

if (process.env.NODE_ENV === "production") {
  module.exports = require("./read.cjs.prod.js").default;
} else {
  module.exports = require("./read.cjs.dev.js").default;
}
```

That would be nicer to migrate to `type: "module"` at the same time.

**Comment by Andarist** [comment]
That's matching the declared interface. It's sort-of a node's problem that they have chosen to break compatibility with the existing tooling.

We'll be "fixing" this - but we can't say when exactly this will happen because it's a breaking change.

**Comment by JounQin** [comment]
If you use `exports` field in `package.json` without any other changes, that would be still compatible for commonjs and native esm at same time.

```jsonc
{
  "exports": {
    "import": "xx.mjs", // notice `.mjs` is required
    "require": "xxx.js" // current commonjs entry
  }
}
```

No `type: "module"` required.

**Comment by Andarist** [comment]
Unfortunately, to my great despair, this is not as easy. Right now you can use `@changesets/read` with ESM in node like this:
```js
import read from '@changesets/read'

read.default()
```
After the proposed change the semantics would change and only this would be possible:
```js
import read from '@changesets/read'

read()
```

So for existing users, this would classify as a breaking change.

**Comment by JounQin** [comment]
I suppose no one will be using this pattern as it's just more rediculous than the original issue.

```js
import read from '@changesets/read'

read.default()
```

**Comment by HenryNguyen5** [comment]
Just ran into this, I was able to work around it via:
```ts
import _readChangesets from '@changesets/read'
// See https://github.com/changesets/changesets/issues/622
const readChangesets =
  _readChangesets.default as typeof import('@changesets/read/dist/declarations/src/index.js')['default']
```
