### ISSUE TITLE
audit warning for outdated ansi-regex subdependency of boxen@1 used by @changesets/cli

### ISSUE THREAD

**Issue by dominikg** [changesets/changesets#684]
## Affected Packages

cli

## Problem

running `pnpm audit` reports a possible security issue with an old version of ansi-regex used by boxen@1.

pnpm audit
```
┌─────────────────────┬────────────────────────────────────────────────────────────────┐
│ moderate            │  Inefficient Regular Expression Complexity in chalk/ansi-regex │
├─────────────────────┼────────────────────────────────────────────────────────────────┤
│ Package             │ ansi-regex                                                     │
├─────────────────────┼────────────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >2.1.1 <5.0.1                                                  │
├─────────────────────┼────────────────────────────────────────────────────────────────┤
│ Patched versions    │ >=5.0.1                                                        │
├─────────────────────┼────────────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-93q8-gq69-wqmw              │
└─────────────────────┴────────────────────────────────────────────────────────────────┘
```
pnpm why ansi-regex
```
@changesets/cli 2.18.1
├─┬ boxen 1.3.0
│ ├─┬ ansi-align 2.0.0
│ │ └─┬ string-width 2.1.1
│ │   └─┬ strip-ansi 4.0.0
│ │     └── ansi-regex 3.0.0
```

## Proposed solution

Given that the latest major version of boxen is 6, please consider upgrading it.

**Comment by Andarist** [comment]
@dominikg would you like to prepare a PR for that?

**Comment by dominikg** [comment]
i tried but didn't find a contributing guide to follow and `yarn && yarn build && yarn test` throws errors even without modifications.

`yarn outdated` shows there are **a lot** of outdated dependencies, some are multiple major versions behind. Notably jest is still at v25, which means no esm support at all. 

This excludes updating boxen to v6 which is one of many packages by Sindre Sorhus that is esm-only now.
So the max version of boxen that would be compatible with this repo in it's current state is v5. 

ps. updating boxen could also fix https://github.com/atlassian/changesets/issues/560
