### ISSUE TITLE
[question] How to format changelog entries?

### ISSUE THREAD

**Issue by dimitrisnl** [changesets/changesets#689]
Is it possible to document how to format the changelog entries?
For example, I want to remove the `Thanks X` part, which is mostly noise when I maintain something alone.

I've seen some PRs & issues floating around, like:
- https://github.com/changesets/changesets/pull/460
- https://github.com/changesets/changesets/issues/161
- https://github.com/changesets/changesets/pull/624

Thank you!

**Comment by Andarist** [comment]
You can write a custom changelog generator like this one:
https://github.com/FormidableLabs/urql/blob/4b58fea48faab268037fe1a2631cfe7c326a0640/scripts/changesets/changelog.js

Notice that it even reuses the stuff from Changesets to accomplish the goal.

That being said - the thank you stuff has already come up a couple of times so I'm willing to make this configurable. Could you propose how such an option should be named and how should it work?

**Comment by dimitrisnl** [comment]
@Andarist I don't believe turning off the 'thank you' part is the best solution. Someone else might just want to change the order of elements, or keep the "thank you" part with different wording.

Making the formatting part more user friendly should do the trick. I'll spend some time tweaking a custom generator to come up with something that serves my needs. I'm happy with this workaround. Sorry for not being more helpful :(

**Comment by Andarist** [comment]
Right, the problem is that customizing possibilities are costing precious maintenance time and it's unclear what people would actually like to be customizable 😉 I try to keep an eye on the reported needs but there has to be a bigger group of people wanting a particular feature to justify the development of that feature.

**Comment by dimitrisnl** [comment]
I'll close this for now, and anyone else who feels that they are missing this feature can bump it.

Thank you @Andarist for the explanation!
