### ISSUE TITLE
Snapshot timestamp is weird

### ISSUE THREAD

**Issue by jakubmazanec** [changesets/changesets#691]
## Affected Packages

@changesets/assemble-release-plan
@changesets/cli (in practice)

## Problem

Snapshot timestamps have format that doesn't intuitively correspond to actual date and time. E. g. few minutes ago changsets CLI used timestamp `202111420026`, but the date is actually `2021-12-04`. Expected date part of the timestamp would be `20211204`, not `2021114`. Also, the timestamp can't be used to order.
The issue is, I think, in the [getSnapshotSuffix](https://github.com/changesets/changesets/blob/c68536edf4c04e7fdf5594ec9c69471cd86fd0ce/packages/assemble-release-plan/src/index.ts#L23) function; functions like `getUTCMonth` are zero-based, and they return number that is not then zero-padded.

## Proposed solution

Maybe use `toISOString` method for generating the timestamp? E.g. `(new Date()).toISOString().replaceAll(/(-|\:|\.|Z|T)/g, '')`.

**Comment by Andarist** [comment]
I agree with you. I don't think that what is currently used is made that way on purpose and I would classify this as a bug.

I don't think that increasing the precision of this timestamp is required though, so something like this should do the trick:
```js
new Date().toISOString().replace(/\.\d{3}Z$/, '').replace(/[^\d]/g, '')
```

Would you like to prepare a PR for this?

**Comment by jakubmazanec** [comment]
Sure, why not.
