### ISSUE TITLE
npm Automation tokens not supported

### ISSUE THREAD

**Issue by b3nThomas** [changesets/changesets#707]
## Affected Packages
`@changesets/cli@2.18.1`

## Problem
`changeset publish` attempts to use the `npm profile get --json` command to work out if 2fa is enabled etc.
When using an Automation level npm token, this throws a 403 error as these tokens literally only have access to read or publish, and I think `npm whoami` too.:
```
13:11:02                      echo //registry.npmjs.org/:_authToken=**** > .npmrc &&
13:11:02                      npm profile get --json
13:11:02                  '
13:11:03  []                   / profile:
[]                   / profile:
[]                   - profile:
[]                   - profile:
[]                   - profile:
[]                   \ profile:
[]                   \ profile:

npm ERR! code E403
13:11:03  npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/-/npm/v1/user
13:11:03  npm ERR! 403 In most cases, you or one of your dependencies are requesting
13:11:03  npm ERR! 403 a package version that is forbidden by your security policy, or
13:11:03  npm ERR! 403 on a server you do not have access to.
13:11:03  {
13:11:03    "error": {
13:11:03      "code": "E403",
13:11:03      "summary": "403 Forbidden - GET https://registry.npmjs.org/-/npm/v1/user",
13:11:03      "detail": "In most cases, you or one of your dependencies are requesting\na package version that is forbidden by your security policy, or\non a server you do not have access to."
13:11:03    }
13:11:03  }
13:11:03  
13:11:03  npm ERR! A complete log of this run can be found in:
13:11:03  npm ERR!     /root/.npm/_logs/2021-12-13T13_11_03_532Z-debug.log
13:11:03  
[Pipeline] }
```

I had to work backwards to find this command as you actually only get this little error message:
```
13:06:31   1 file changed, 1 insertion(+), 1 deletion(-)
13:06:32  78🦋  info npm info @******/*****
13:06:33  error parsing json: 
13:06:33  SyntaxError: Unexpected end of JSON input
13:06:33      at JSON.parse (<anonymous>)
13:06:33      at jsonParse (/usr/src/app/node_modules/@changesets/cli/dist/cli.cjs.dev.js:601:17)
13:06:33      at getTokenIsRequired (/usr/src/app/node_modules/@changesets/cli/dist/cli.cjs.dev.js:651:14)
13:06:33      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
A workaround is to simply set the `GITHUB_ACTIONS` environment variable which prevents these checks from being made.
Obviously this isn't ideal.

## Proposed solution
Document the workaround somewhere, or add a cli option to `publish` to skip the `npm profile` checks.

**Comment by Andarist** [comment]
Could you tell me a little bit more about your setup? Are you running this locally? Are you running this on CI? Which CI?

FYI I'm using automation tokens without any problems with GitHub Actions.

**Comment by b3nThomas** [comment]
Sorry, I'm running on Node16 in Docker via Jenkins CI. I've got my changeset status and versions steps all working nicely, however when I try and publish using my automation npm token, I got the above mentioned error `SyntaxError: Unexpected end of JSON input`. These are my steps:
```groovy
    // Add mandatory git / npm creds to container for publishing
    withCredentials([
        usernamePassword(credentialsId: globals('github_credentials_id'), usernameVariable: 'git_user', passwordVariable: 'git_token'),
        string(credentialsId:'npm_publish_token', variable: 'npm_token')
    ]) {
        sshagent([globals('github_ssh_agent')]) {

            sh('''
                docker exec -t ''' + container + ''' /bin/sh -c "
                    git config --global user.email ''' + git_user +'''@xxxxxxxx.com &&
                    git config --global user.name ''' + git_user + ''' &&
                    echo \"//registry.npmjs.org/:_authToken=$npm_token\" > .npmrc
                "
            ''')
        }
    }

```

```groovy
    // Create commit on base branch, publish, tidy up.
    sh("""
        docker exec -t ${container} /bin/sh -c "
            git add package*.json &&
            git commit -m \"${new_version}\" &&
            GITHUB_ACTIONS=foo npx changeset publish &&
            rm .npmrc
        "
    """)
```

If I don't provide the `GITHUB_ACTIONS` variable, `publish` will by default try and use `npm profile` commands to check if the token has 2fa affiliated with it. Automation tokens are forbidden from using `npm profile` so it errors.
https://github.com/changesets/changesets/blob/c68536edf4c04e7fdf5594ec9c69471cd86fd0ce/packages/cli/src/commands/publish/npm-utils.ts#L65

**Comment by Andarist** [comment]
The problem is not the lack of `GITHUB_ACTIONS` env variable but rather that `isCI` fails to recognize Jenkins CI as CI environment. Do you know if there is any Jenkins-specific variable that we could use to check if the code is running in Jenkins or not?

**Comment by Andarist** [comment]
There is some chance that [this PR](https://github.com/changesets/changesets/pull/708) will help to recognize Jenkins CI correctly. However, I've seen some issues that Jenkins might currently not be that easy to recognize - so I guess we'll have to test this empirically.

**Comment by b3nThomas** [comment]
Thanks for the steer here. I see that the following criteria is required to identify Jenkins in the `ci-info` package:
https://github.com/watson/ci-info/blob/1f890078805447ed39b17a6ad136356a7d5cd68b/vendors.json#L120-L125

I think the issue is that I'm running changesets on Node inside Docker so the standard Jenkins env vars haven't been passed through to Docker, unless I explicitly do it myself.

I feel like a cli option to opt in to this behaviour could be really valuable in this case though, for example `npx changesets publish --ci`.

Also, it would be great if there was some better error handling around that `jsonParse` error to better inform the user what's happened. Maybe just logging actual error or something:
https://github.com/changesets/changesets/blob/c68536edf4c04e7fdf5594ec9c69471cd86fd0ce/packages/cli/src/commands/publish/npm-utils.ts#L68

**Comment by b3nThomas** [comment]
Yup I'm using npm8+ for my builds. Odd that I'm not getting the correct logs when `jsonParse` errors 🤔.

I tried `CI=true` and can confirm that it works absolutely fine 🎉  Thanks for this.

**Comment by Andarist** [comment]
> I'm using npm8+ for my builds. Odd that I'm not getting the correct logs when jsonParse errors 🤔.

I've created a PR to address this: https://github.com/changesets/changesets/pull/710
