### ISSUE TITLE
Conditional Changeset Publish 

### ISSUE THREAD

**Issue by JacobMGEvans** [changesets/changesets#711]
Greetings, 

I don't know if I misunderstand the documentation or something is missing. I, however, hope to be able to run the GitHub Action creating the changeset PR and only trigger the Release/Publish once the changeset PR has been merged. 

I would appreciate any insight or clarification on the documentation as well.

**Comment by Andarist** [comment]
> I don't know if I misunderstand the documentation or something is missing. I, however, hope to be able to run the GitHub Action creating the changeset PR and only trigger the Release/Publish once the changeset PR has been merged.

This is exactly how it works.

> I would appreciate any insight or clarification on the documentation as well.

The simplified pseudo-code of the `changesets/action` would be smth like this:
```
if hasChangesetFiles
  createOrUpdateVersioningPR
else
  unreleasedPackages = getUnreleasedPackaged()
  releasePackages(unreleasedPackages)
```

Note that when you merge the versioning PR to your base branch you effectively remove changeset files from the `.changeset` directory and thus the `else` branch "kicks in".

**Comment by JacobMGEvans** [comment]
Thank you for your response!
