### ISSUE TITLE
Nit: Cursor positioning is odd now

### ISSUE THREAD

**Issue by Noviny** [changesets/changesets#72]
![image](https://user-images.githubusercontent.com/15622106/58775392-96d65500-8608-11e9-9292-4f99f8956b9f.png)

When typing a summary, the cursor is spaced away form the text. The above image has no character after the question mark but is oddly not next to it.

This keeps putting me off slightly and I should probably dig into what it is.

**Comment by mitchellhamilton** [comment]
I've solved this in my work on #52(will open a PR soon)

**Comment by Noviny** [comment]
❤️ Closing this then
