### ISSUE TITLE
Pre-release mode for a subset of packages

### ISSUE THREAD

**Issue by Rugvip** [changesets/changesets#724]
## Problem

Hi! We're looking for a way to have a bit more flexibility in the release schedules of individual packages within a monorepo, especially with regards to pre-releases. We're wondering if the following is on the either already possibly or on the roadmap, desired, feasible, and a overall a good idea: **Enable pre-release mode for a subset of packages within a monorepo**

## Proposed solution

The idea is that a set of packages within a monorepo have a more infrequent release cadence, for example packages at version `1.x` or above. The rest of the packages are released more frequently, sticking to the same example they will all be at version `0.x`. While the release cadence of the `1.x` packages is lower, we'd sill want pre-releases of those packages with the same cadence as the `0.x` releases. When entering pre-release mode for the `1.x` packages, the `0.x` would switch to and bump their dependencies on `1.x` packages as needed. This is assumed to be safe from an implementation point of view, and we also assume that none of the `1.x` packages have dependencies on any `0.x` packages.

A more concrete example of this would be the following release flow, with the packages `foo` and `bar`:

```json5
// packages/foo/package.json
{
  "name": "foo",
  "version": "0.1.0",
  "dependencies": {
    "bar": "^1.0.0"
  }
}
// packages/bar/package.json
{
  "name": "bar",
  "version": "1.0.0"
}
```

- Initial state:
  `foo@0.1.0`, dependency `bar@^1.0.0`
  `bar@1.0.0`

-  Release 1, enable pre-release and do a `minor` bump of `bar`:
  `foo@0.1.1`, dependency `bar@^1.1.0-next.0`
  `bar@1.1.0-next.0`

-  Release 2, `patch` bump of both `foo` and `bar`:
  `foo@0.1.2`, dependency `bar@^1.1.0-next.1`
  `bar@1.1.0-next.1`

- Release 3, exit pre-release:
  `foo@0.1.3`, dependency `bar@^1.1.0`
  `bar@1.1.0`

The way that this pre-release mode would be enabled is TBD, but it could be an explicit list of packages, or perhaps based on filter criteria such as `version >= 1.0.0`.

Looking both for feedback on the idea and whether it fits in. If it's something that's desired then we're also happy to look into if it's something we can contribute.

**Comment by Andarist** [comment]
Q: why in the example it is desired for foo package to stay outside of the pre mode if its dep is in pre mode? Isnt this confusing? What is the downside of having it in the pre mode too?

**Comment by Rugvip** [comment]
> Q: why in the example it is desired for foo package to stay outside of the pre mode if its dep is in pre mode? Isnt this confusing? What is the downside of having it in the pre mode too?

Pre-releases don't communicate the same semver guarantees as a regular line of releases does. It's nice to be able to rely on semver and patch bumps of the `0.x` packages and only do breaking `minor` releases when needed. It's also less aesthetically pleasing and doesn't quite convey the same sense of stability as a `0.x` version does. Thinking the sense of stability you're getting of a package is something along `1.x` > `0.x` > `1.x-next.x` > `0.x-next.x`.

**Comment by Rugvip** [comment]
We've gone back another round and though about this some more. It's still something we think is the best solution for us as we have this mix of more and less mature packages that we want to develop together. Something we've realized that we want to change from the initial plan is to have the `0.x` packages depend on the most recent mainline release of `1.x` package, and bringing those in from NPM rather than depending on them directly from the repo. That means all `1.x` packages need to more or less always be in prerelease mode in order to force package downloads.

Question then is if this is something you think makes sense to ship as an experimental feature in changesets in some form. The main alternative we're considering right now is to replace `changeset version` in our workflow with a custom script that builds on top of the changesets packages to implement to suggested functionality.

**Comment by Rugvip** [comment]
Now we're full circle back to more or less straight prereleases. The workflow for bumping the `0.x` post `1.x` releases ends up being too cumbersome, to the point where it's as tedious as moving things to a separate repo, but also more confusing. Will close this as an ask, but potentially update with where we end up in the future :grin:

**Comment by jacobrask** [comment]
This is useful if you have unrelated packages in a monorepo. It can be eslint config packages or CLIs that have no reason to be versioned together with your design system components.
