### ISSUE TITLE
[Question] Major version not bumped

### ISSUE THREAD

**Issue by TheeMattOliver** [changesets/changesets#736]
Howdy

Noticed that when I released a major version release today, Changesets successfully published to npm but didn't update the version on Github.

Compare:

https://github.com/graphemic/prettier-config/releases/tag/v0.8.2

to:

https://github.com/graphemic/prettier-config/blob/main/CHANGELOG.md

and note that the npm package successfully bumpedf to 1.0:

https://www.npmjs.com/package/@graphemic/prettier-config

Wondering if there's a step I missed?

**Comment by Andarist** [comment]
I'm not sure if I understand the reported problem. As far as I can see the v1.0.0 release on GitHub was created by our action: https://github.com/graphemic/prettier-config/releases/tag/v1.0.0

**Comment by TheeMattOliver** [comment]
We can close, misfire on my part, sorry about that Mateusz!
