### ISSUE TITLE
Add docs for the fixed mode

### ISSUE THREAD

**Issue by Andarist** [changesets/changesets#754]
We've landed https://github.com/changesets/changesets/pull/690 without the docs but it would be great to have at least basic information about this new feature in the docs.

**Comment by akphi** [comment]
Is the doc basically https://github.com/changesets/changesets/issues/581#issuecomment-830807176 or you want to have something similar to https://github.com/changesets/changesets/blob/main/docs/linked-packages.md with a section on `linked` vs `fixed`?
