### ISSUE TITLE
Do not remove changelog from Pull Request created by changeset action

### ISSUE THREAD

**Issue by vtereshyn** [changesets/changesets#771]
The flow is following:
- create a Pull Request with new feature to the `main` branch
- merge this PR to `main` branch and do `prerelease`
- changeset github action creates a PR with `release` and changelog with what has been changed

When this flow repeats with another feature changelog with previous feature is removed and only latest is available there. Is it possible to not remove previous changelogs so I can have all changelogs of unreleased packages?

Thanks

**Comment by Andarist** [comment]
Just to clarify - you want the changelog in the PR's body to contain all changes from the current prerelease cycle. Did I get this right?

**Comment by vtereshyn** [comment]
@Andarist yes, exactly.

I am trying to build next flow:

- merge to `main` branch
- do prerelease and deploy everything to `dev` environment
- create PR to release all packages (NOT prerelease)
- merge that PR to `main` and do release of packages and deploy everything to prod
- generate proper changelog with all changes

**Comment by Andarist** [comment]
Hm, I think this is somewhat easy to script. You'd have to just prepare a workflow that would branch out from your `dev`, call `changeset pre exit` there, commit stuff, and wrap this in a PR. Perhaps even `changesets/action` could be used to simplify this (if used properly conditionally etc) but maybe we'd have to accept some new options to configure the target branch of the PR itself.

If you'd push out stuff after calling `changeset pre exit` you would end up basically with what you want - a PR containing all changelogs updated based on all changeset files added in the current prerelease cycle.

**Comment by vtereshyn** [comment]
@Andarist 
yeah, my workflow is something that I described above. I can expand on this:
We have only one main branch called `main`. From this branch we're automatically deploying frontend and backend to dev when something merged to `main`. If we want to make release to production we're doing that manually. 

So the flow now is next:
1. Create a PR with bug/feature
2. Merge PR to `main`
3. Do prerelease and deploy to dev:
```
		git checkout main
          yarn changeset pre enter next
          yarn changeset version
          git add .
          git commit -m "ci(changesets): prerelease"
          yarn changeset publish
          yarn changeset pre exit
          git add .
          git commit -m "ci(changesets): prerelease"
          git push --follow-tags
```
As you can see because of prerelease I need to commit changes 2 times so `pre.json` will be there. It will be great to not have that `pre.json` and have an ability to prerelease packages like `lerna` does.
4. changesets/action will create/update release PR
There are some problems here. For example it will always have conflicts with `main` branch.
5. Release to prod – whenever we ready we merge PR created by `changesets/action`

**Comment by Andarist** [comment]
> But I really need to update versions of all packages in package.jsons.

Why though? Could you expand on this one? 

> As you can see because of prerelease I need to commit changes 2 times so pre.json will be there.

What does happen if you don't commit this? 

> There are some problems here. For example it will always have conflicts with main branch.

Why? I mean - if a versioning PR has been branched off from `main` how it can end up with conflicts?
