### ISSUE TITLE
process.env.npm_config_registry ignored 

### ISSUE THREAD

**Issue by spezzino** [changesets/changesets#781]
## Affected Packages

@changesets/cli

## Problem
process.env.npm_config_registry ignored when publishing using changesets

If .yarnrc has a registry set, that value is used instead, if not, then the default registry in [getCorrectRegistry](https://github.com/changesets/changesets/blob/5a2a59a37b7fb31e17414579b470402d3016e28e/packages/cli/src/commands/publish/npm-utils.ts#L28) is used.

To reproduce
1. Clone this repo
2. yarn install
3. `npm_config_registry=https://my-private-registry.com/api/npm/ yarn release`

result
`npm ERR! 401 Unauthorized - GET https://registry.npmjs.org/-/npm/v1/user`

note: the command fails due to my npm config, that's not the problem. It should be checking my-private-registry.com instead of npmjs.org

I tried to debug the `getCorrectRepository` method by printing the current env vars, and I see the value for the variable is
`"npm_config_registry": "https://registry.yarnpkg.com",` even after supplying my own in the command line.

yarn version 1.22.17

## Proposed solution

a couple of issues here already mentioned the possibility of having the registry declared in .changeset/config.json
or maybe using a different env var to override npm/yarn values

**Comment by spezzino** [comment]
ended up using YARN_REGISTRY to set the private registry value. 
This effectively sets the correct registry for  npm_config_registry at the moment is read in getCorrectRepository

**Comment by Andarist** [comment]
Huh, this is very strange - but I've confirmed that this is, indeed, how Yarn Classic behaves. I don't think there is a way to access this overridden `process.env.npm_config_registry` in this case, so I'm not sure how we even could "do better" here.
