### ISSUE TITLE
Use an alternative indicator for selecting packages

### ISSUE THREAD

**Issue by samrose3** [changesets/changesets#809]
## Affected Packages

`pkg:@changesets/cli`

## Problem

When introducing Changesets to our repo, contributors had some difficulty identifying which packages were selected when creating a new changeset.

This was due to insufficient color contrast between the active and inactive checkmark ✔️ beside the package. Below is a screenshot example of a terminal color scheme with low contrast when selecting packages:

<img width="334" alt="low-contrast-example" src="https://user-images.githubusercontent.com/11774595/169551146-edffabb7-7cab-4674-8406-efc0d3814048.png">
 
## Proposed solution

An alternative selection indicator that doesn't rely on color may be a more inclusive solution. Some ideas include:

- using a different icon/symbol to indicate a package as unselected (✖️ , ➖ , etc)
- removing the icon when unselected (no icon indicator when inactive)

**Comment by Andarist** [comment]
I'm totally on board with the idea. Have you experimented with any changes there? Is the flow without an icon for packages that are not selected understandable by you?

**Comment by samrose3** [comment]
@Andarist I've proposed two alternatives:

- using a radio on/off indicator
- using the same ✔️ for the selected (enabled) state and no indicator (`" "`) for unselected (disabled)

**Comment by ssalbdivad** [comment]
I encountered a similar issue trying to set up changesets for my monorepo. This was using WSL + Windows Terminal:

![image](https://user-images.githubusercontent.com/10645823/171008269-de30348f-d2f9-4399-8c97-b88742114aec.png)

In general, color/emoji support is good, but for some reason pressing space had no impact on the rendered checkmark, so it was impossible to tell which packages were selected. Maybe has something to do with my terminal font?

Running the same command from within VSCode's built-in terminal (same shell) yields better results:

![image](https://user-images.githubusercontent.com/10645823/171008702-6292dee2-df8d-4b49-bb49-f2d5d420b455.png)

Without worrying too much about the nuances of which terminal/font/platform combinations result in these problems, I'd definitely recommend adopting either of the solutions proposed by @samrose3 to ensure changesets users don't have to worry about those things either 😸
