### ISSUE TITLE
changeset publish --registry not work

### ISSUE THREAD

**Issue by sudongyuer** [changesets/changesets#832]
## Problem
I use --registry to point my private registry but it not work,it still poin to npmjs.org

![image](https://user-images.githubusercontent.com/76603360/172333050-e4b17255-f969-4a25-9d47-ba5577e06e6e.png)

**Comment by mathulbrich** [comment]
For changeset I think you need to specify the registry on `publishConfig` option inside your `package.json`.

```json
{
  "publishConfig": {
    "registry": "<<YOUR CUSTOM REGISTRY HERE>>"
  }
}
```

That inside of each of your packages if you have more than one.
