### ISSUE TITLE
[Feature Request] Support `config.js` for dynamic configs

### ISSUE THREAD

**Issue by CobyPear** [changesets/changesets#838]
## Affected Packages

I think pkg:cli and/or pkg:config

## Problem

I do not want to manually update `.changesets/config.json`. I want to be able to use a `config.js` file out of the box so that I can write logic to dynamically set properties in my config.

## Proposed solution

Nothing specific at the moment. I see that this was supported in v1 but was removed -likely for good reason- but I'd like to know more if possible. I was unable to find anything looking through the changelogs.
Many other tools support both `.json` and `.js` files, so I would look there to get a possible solution if this is something that is worth supporting.

**Comment by Andarist** [comment]
Static configs are usually better when it comes to caching and stuff but we are not concerned about this here. I **think** that I would be OK with adding this. I would like to double-check with @mitchellhamilton though, to hear out his opinion.

Also note that with ESM in node this might be slightly more complicated than implementing `require(path.join(projectPath, '.changeset', `config.js`))`

**Comment by mitchellhamilton** [comment]
The reasoning behind static configs was primarily to allow tools like https://github.com/changesets/bot to exist and be able to say things like "these are the packages that will be released with these versions" without having to execute user code.

I'd mostly say, what do you want to be dynamic in the config?

**Comment by CobyPear** [comment]
Thanks for the reply! We wanted a way to add linked or fixed packages dynamically. Turns out we currently don’t need either, but we may in the future.

**Comment by Andarist** [comment]
Is it an option to run a script before Changesets to regenerate the config? That way you could still have it dynamic while Changesets could see it as static.

**Comment by CobyPear** [comment]
> Is it an option to run a script before Changesets to regenerate the config?
That's a fair solution that should work for us. Thank you for the input!
