### ISSUE TITLE
Local npm dependency support

### ISSUE THREAD

**Issue by tivac** [changesets/changesets#846]
## Affected Packages

CLI

## Problem

My monorepo uses npm's support for dependencies like `"foo": file:../foo` to ensure that cross-linked packages within the repo always use the latest, local version of the code. I would like to move from lerna to changesets for releasing, but it doesn't seem like they support `file:` references as dependencies yet?

I've been experimenting with this in this repo

https://github.com/tivac/changesets-test

and most commands end up telling me the following:

> Package "@tivac/changesets-test-b" must depend on the current version of "@tivac/changesets-test-a": "1.1.0" vs "file:../a"

Is there a more changesets-y way to manage this? I specifically do **not** want to install the latest version of the other package within the monorepo, I'm often making changes across multiple packages and I'm not clear what the workflow for that would be. I know xstate uses changesets so I dug around in their `package.json`s but didn't see anything that looked like it answered my questions.

## Proposed solution

I'd love if changesets supported the `file:` dependencies natively, and automatically rewrote them to the latest version of the sibling package before publishing like lerna does currently.

**Comment by tivac** [comment]
I'm not really interested in using a 3rd-party package manager if I can avoid it.

I did some further testing on removing the `file:` references, and it looks like I can maybe just drop that entirely and npm will do the correct thing and create symlinks to the other packages? If that's the case then I think my issue is moot and I'll just need to do a pass on updating all those existing dependencies.

Thanks for the info @Andarist!

**Comment by Andarist** [comment]
> I did some further testing on removing the file: references, and it looks like I can maybe just drop that entirely and npm will do the correct thing and create symlinks to the other packages?

If using npm workspaces it should do that. Just note that for that to happen your dependency needs to have a version matching your requested dependency range. If you won't be doing manual edits and you will use Changesets for versioning then it should always hold true.
