### ISSUE TITLE
[Question] Can i add a custom question in changeset command and then response is added to changeset

### ISSUE THREAD

**Issue by ajayjindal** [changesets/changesets#877]
## Question

- Is there a way to add a custom question to changeset questionnaire?
   - for example: `Enter Jira ticket:` (after all the main questions are asked)
   
Then i would want to add this to markdown file generated (prepended to description)

This would help my team to enforce having JIRA ticket always present in changelogs for each change.
#### Any suggestion on how i can achieve this?

**Comment by Andarist** [comment]
We are discussing the customization possibilities for this prompt here: https://github.com/changesets/changesets/issues/899 . Your input would be very much welcome there.
