### ISSUE TITLE
Hide ignored packages from prompt

### ISSUE THREAD

**Issue by equinusocio** [changesets/changesets#883]
## Affected Packages

`pkg:cli`

## Problem

When a package is set as ignored via configuration, such package should not be listed in the version prompt while selecting changed packages.

If an ignored package is accidentally selected while selecting other packages, the PR creation and release will fail, giving the following error:

<img width="752" alt="Screenshot 2022-07-22 at 16 37 44" src="https://user-images.githubusercontent.com/10454741/180463809-aad3a677-072e-4d51-9799-984aa4508594.png">

## Proposed solution

An optin configuration that hiides packages from the CLI prompt while creating the changeset.

**Comment by melanieseltzer** [comment]
@equinusocio Looks like it was added in [v2.23.2](https://github.com/changesets/changesets/releases/tag/%40changesets%2Fcli%402.23.2) 🙂

**Comment by equinusocio** [comment]
Can't find any 2.32.2 on npm...
