### ISSUE TITLE
Should `version` command have `--since` flag?

### ISSUE THREAD

**Issue by dotansimha** [changesets/changesets#897]
## Affected Packages

version/cli?

## Problem

As part of the work we do at The Guild in our repos, we are using `snapshot` releases for releasing canary versions for PRs. 

To do that, we are using `version --snapshot alpha` and then `publish --tag alpha`. This works perfectly fine. 

When Changesets begin to stack in the target/main branch (master/main), we are seeing a kinda annoying behavior in PRs. The `version` command includes changesets files that are coming from `master`, instead of using only the changes relevant to the specific PR.  

This causes inconsistent results with our custom GitHub Action (that runs `version` as described above). We can see that the Changesets bot detects only the relevant packages:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/3680083/182679669-e833082e-3699-4927-ad9a-822ed9540af2.png">

While our bot/action (that gets the output of version+publish) has published more packages (because we are those changesets in master):

<img width="935" alt="image" src="https://user-images.githubusercontent.com/3680083/182679630-82b4a30c-319c-4dbd-97d6-d2d057f1a65a.png">

## Proposed solution

Similar to `status` command, we can provide `--since` flag to `version` flag, and point to the target branch in a PR. This way, the `version` command will make sure to include only `changesets` files that were added in that specific PR (similar to what changesets-bot is doing in the PR comments) 

@Andarist @mitchellhamilton @jakubmazanec what do you think? I can open a PR if that makes sense.

**Comment by Andarist** [comment]
> Similar to status command, we can provide --since flag to version flag, and point to the target branch in a PR. This way, the version command will make sure to include only changesets files that were added in that specific PR (similar to what changesets-bot is doing in the PR comments)

We'd have to ensure to still version all dependant packages of all the packages with changesets included in the given PR. Otherwise, you wouldn't be quite able to test those with the newly released snapshot dependencies.

**Comment by dotansimha** [comment]
> We'd have to ensure to still version all dependant packages of all the packages with changesets included in the given PR. Otherwise, you wouldn't be quite able to test those with the newly released snapshot dependencies.

Isn't that should be a by-product of the `changeset` of a specific PR, instead of all changesets available in the branch? At least for snapshot releases, since we wish to have a release based on the PR changes only, even if there are more changes on the target branch.

**Comment by Andarist** [comment]
> Isn't that should be a by-product of the changeset of a specific PR, instead of all changesets available in the branch? 

Yes. I just mean that we can't *only* release stuff from the changesets specific to a PR because those might always implicitly pull dependants into the release and that we should have tests etc verifying that this actually happens. Those dependant packages could have more changesets for them (ones unrelated to the PR in question) or they could have no changesets at all - in both scenarios they should be released though.

Actually, even dependencies should be pulled into the release too - but those could be filtered by having some changesets or not.

**Comment by dotansimha** [comment]
Got it now, thanks for clarifying @Andarist , this does makes sense. I'm closing this one :)

**Comment by Andarist** [comment]
@dotansimha note that this doesn't make this feature totally obsolete - it's just that perhaps the generated release with this should contain more than just packages mentioned in the given subset of changesets. The final generated release could be still a little bit smaller than a release based on all of the changesets.
