### ISSUE TITLE
`changeset tag` creates tags that already exist

### ISSUE THREAD

**Issue by gamertike** [changesets/changesets#902]
## Affected Packages

`@changesets/cli`

## Problem

When using `changeset tag` (specifically in a workflow), it creates tags that already exist

### What happened

The following workflow has failed due to `changeset tag` creating tags that already exist instead of skipping them.
https://github.com/guildedts/guilded.ts/runs/7689876479?check_suite_focus=true#step:7

### Expected behaviour

These tags should have been skipped so git wouldn't throw an error when i try to push tags.

```
🦋  Skipping tag (already exists):  @guildedts/builders@0.2.8
🦋  Skipping tag (already exists):  @guildedts/framework@0.2.2
🦋  Skipping tag (already exists):  guilded-api-typings@0.9.0
🦋  Skipping tag (already exists):  guilded.ts@0.14.1
🦋  Skipping tag (already exists):  @guildedts/rest@0.10.2
🦋  Skipping tag (already exists):  @guildedts/ws@0.4.3
```

The repo that is experiencing this is [guildedts/guiled.ts](https://github.com/guildedts/guilded.ts).

**Comment by Andarist** [comment]
See the thread here: https://github.com/changesets/action/issues/201#issuecomment-1206237040
