### ISSUE TITLE
Using `--snapshot` breaks with "@changesets/assemble-release-plan": "5.2.0" 

### ISSUE THREAD

**Issue by logan-anderson** [changesets/changesets#910]
## Affected Packages

```
"@changesets/assemble-release-plan": "5.2.0"
```

## Problem

Recently, I was doing updates to our monorepo and while doing so "@changesets/assemble-release-plan" got updated from "5.1.3" to "5.2.0". When using `changeset version --snapshot` I get the following error.

```
error TypeError: Cannot read properties of undefined (reading 'prereleaseTemplate')
🦋  error     at Object.assembleReleasePlan [as default] (/home/runner/work/***/***/node_modules/.pnpm/@changesets+assemble-release-plan@5.2.0/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:562:72)
🦋  error     at version (/home/runner/work/***/***/node_modules/.pnpm/@changesets+cli@2.18.0/node_modules/@changesets/cli/dist/cli.cjs.dev.js:566:60)
🦋  error     at async run$2 (/home/runner/work/***/***/node_modules/.pnpm/@changesets+cli@2.[18](https://github.com/tinacms/tinacms/runs/7772584139?check_suite_focus=true#step:11:19).0/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1256:11)
 ELIFECYCLE  Command failed with exit code 1.
```

## Proposed solution

In the package.json if I force the version back to "5.1.3" the error goes away.

Since we are using pnpm this can be done by

```
"pnpm": {
    "overrides": {
      "@changesets/assemble-release-plan": "5.1.3"
    }
  }
```
in the root package.json

I also asked a question about it [here](https://github.com/changesets/changesets/discussions/908) but after digging around I realized it was a bug. 

### More info
- Action with the error: https://github.com/tinacms/tinacms/runs/7770620785?check_suite_focus=true
- PR that error was (before I forced the version to "5.1.3") happening on: https://github.com/tinacms/tinacms/pull/3088
- Action that is running: https://github.com/tinacms/tinacms/blob/main/.github/workflows/publish-pr.yml

**Comment by Andarist** [comment]
Are you using any custom composition of our packages? Or are you just interacting with the `@changesets/cli`?

**Comment by Andarist** [comment]
For the record - I've reproduced the issue in your repository and gonna take a closer look at this tomorrow.

**Comment by Andarist** [comment]
I'm not sure why but [this commit](https://github.com/tinacms/tinacms/commit/09e50a1fe4bf2dc5f63f873aebfaccc0c3413412) has updated `@changesets/assemble-release-plan` within the lock file but the same didn't happen for `@changesets/config`. 

I've created a compatibility fix [here](https://github.com/changesets/changesets/pull/914) but you can probably fix it today by:
- upgrading `@changesets/cli`
- somehow forcing `@changesets/config` to get updated in your lockfile without upgrading `@changesets/cli` itself (unsure how to do it with pnpm, you could try to remove the Changesets-related entries from it and then running pnpm which, hopefully, should regenerate the relevant parts)

Alternatively you can wait for the release of this fix and somehow force `@changesets/assemble-release-plan` update in your lock file.

**Comment by logan-anderson** [comment]
Thanks! I updated `@changesets/cli` and it is working again!
