### ISSUE TITLE
fix(cli): `changeset tag` does not respect `ignore`

### ISSUE THREAD

**Issue by jjangga0214** [changesets/changesets#916]
## Affected Packages

`@changesets/cli`

## Problem

`changeset tag` creates git tag for a package even when the package is `"private": true` and specified in `ignore` array in the config.

**Comment by Andarist** [comment]
Duplicate of https://github.com/changesets/changesets/issues/833

**Comment by Andarist** [comment]
I would gladly accept a PR fixing this 😉

**Comment by jjangga0214** [comment]
Oh I see. Closing as duplicated.
