### ISSUE TITLE
package version not bump when devDependencies package in workspace update

### ISSUE THREAD

**Issue by xieqiaoyu** [changesets/changesets#921]
## Affected Packages
@changesets/cli: 2.24.3

## Problem
I have package A and B in a monorepo and A have package.json below
```
{
  "name": "@scope/A",
  "version": "1.0.0",
  ...
  "dependencies": {
    ...
  },
  "devDependencies": {
    "@scope/B": "workspace:1.0.0",
     ...
  }
}
```

After I add package B in changeset  and run `changeset version` 

the package.json of A become:

```
{
  "name": "@scope/A",
  "version": "1.0.0",
  ...
  "dependencies": {
    ...
  },
  "devDependencies": {
    "@scope/B": "workspace:1.0.1",
     ...
  }
}
```

version of B is bumped  but the version of A is not.

if I move B from devDependencies to dependencies , repeat the above operation. both A and B version bumped 

I don't know if it is as expected or i did something wrong ?

**Comment by Andarist** [comment]
This is expected. A a change of dev dependency shouldn't affect the release of the package. We need to adjust the range itself in the `devDependency` to keep everything in sync, but rarely the dependant package should be bumped in such a case. If a dev dep is a build tool or something like that and a change in it requires a new release of its dependants then it's recommended to create an explicit changeset for those dependants.

**Comment by xieqiaoyu** [comment]
In my case Package A is a frontend ssr  project and package B is a frontend component lib  . Package B will be packed into dist during package A's building stage, so I put package B into `devDependency` because Package A don't need Package B in product environment. Since the  behavior is expected , I can close this issue, Thanks for the reply ！
