### ISSUE TITLE
Inconsistent list markers in generated CHANGELOG files

### ISSUE THREAD

**Issue by kachkaev** [changesets/changesets#938]
## Affected Packages

~`@changesets/apply-release-plan`~ - not anymore with https://github.com/changesets/changesets/pull/905

## Problem

I’ve noticed inconsistent list markers in some CHANGELOG files, i.e. hyphen alternating with asterisk. Examples:

`-` `*` `-` `-` from https://github.com/changesets/changesets/pull/901:

https://github.com/changesets/changesets/blob/6337ae31874a2d080a1fa342a76fd320aea4c60e/packages/cli/CHANGELOG.md?plain=1#L21-L33

`-` `*` `*` from https://github.com/changesets/changesets/pull/763
https://github.com/changesets/changesets/blob/6337ae31874a2d080a1fa342a76fd320aea4c60e/packages/cli/CHANGELOG.md?plain=1#L155-L163

`-` `*` `-` `*` `-` `-` from https://github.com/changesets/changesets/pull/750: 

https://github.com/changesets/changesets/blob/6337ae31874a2d080a1fa342a76fd320aea4c60e/packages/cli/CHANGELOG.md?plain=1#L173-L185

The marker flicks between every two sibling entries except the one about dependency updates.

This is an artifact of Prettier v1 which was used in this repo until https://github.com/changesets/changesets/pull/905.

Technically speaking,

```markdown
- hello

* world

- 42
```

are three separate unordered lists, according to [the markdown spec](https://spec.commonmark.org/0.28/#example-264).

Asterisks were being introduced because of an old bug in Prettier (https://github.com/prettier/prettier/issues/4369), which was fixed in v2.1. When raw CHANGELOG markdown contained two empty lines between list items, Prettier treated them as `</ul><ul>` and flicked the marker.

## Proposed solution

I started creating this issue after noticing `-` `*` `-` [in own CHANGELOG files](https://github.com/blockprotocol/blockprotocol/commit/e02a8977024ffe269760c25eb863bac35785e3ec#diff-444b964318595e197be718996ca748796f300ddf73960b0bf38cd13a9271c68aR9), but then discovered a fix in https://github.com/changesets/changesets/pull/905. Glad to know that the problem is permanently fixed!

CHANGELOG files in this repo still contain chunky markdown lists, so I’ve opened this issue anyway to flag it. Feel free to just close it if you don’t see value in replacing `*` with `-`. This mini-research can still be useful for someone.

## PS

Changesets is one of my favourite monorepo tools! Love it! 😍

**Comment by Andarist** [comment]
> CHANGELOG files in this repo still contain chunky markdown lists, so I’ve opened this issue anyway to flag it. Feel free to just close it if you don’t see value in replacing * with -. This mini-research can still be useful for someone.

I guess that this can cause this markdown to be incorrectly rendered by some renderers, right? So it potentially would still be worth fixing 🤔 

> Changesets is one of my favourite monorepo tools! Love it! 😍

Thanks! ❤️

**Comment by kachkaev** [comment]
> I guess that this can cause this markdown to be incorrectly rendered by some renderers, right?

Hypothetically yes, because essentially they contain  
`<ul><li>...</li></ul><ul><li>...</li></ul><ul><li>...</li></ul>`
instead of
`<ul><li>...</li><li>...</li><li>...</li></ul>`
