### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by tom-sherman** [changesets/changesets#957]
## Affected Packages

@changesets/cli

## Problem

Missing packages when running `changeset add`.

I'm in a pnpm workspace where I have packages under `packages/` and `libs/`, but the packages inside `libs/` aren't picked up by changsets.

## Proposed solution

Changesets should either infer my package paths from `pnpm-workspace.yaml` or allow me configure this in the config.

**Comment by Andarist** [comment]
IIRC this should already work OK - could you check what happens [here](https://github.com/Thinkmill/manypkg/blob/b8b914441995ad267a490251d443665fb999e32b/packages/get-packages/src/index.ts#L64-L72) in your case?

**Comment by tom-sherman** [comment]
Thanks for the stear, it appears that I have a leftover `workspaces` key in my `package.json` that doesn't include `libs/`, this was causing `getPackages` to think I was using yarn workspaces, which I'm not. Removing the `workspaces` key in `package.json` fixes the issue.

I suppose (if anything) this is a bug with the heuristics in `getPackages`, not changesets. I'll raise an issue of there.
