### ISSUE TITLE
Fixed packages are only bumped up major version regardless of changeset specified version type

### ISSUE THREAD

**Issue by walt1992** [changesets/changesets#963]
## Problem

I hava two packages `a@1.0.0` and `b@1.0.0` that a is depend on b.

and my config.json looks like below
```
{
  "$schema": "https://unpkg.com/@changesets/config@2.0.1/schema.json",
  "commit": false,
  "fixed": [["a", "b"]],
  "access": "restricted",
  "baseBranch": "main",
  "updateInternalDependencies": "patch",
}

```

In this condition, If I made a change on package `a` and made changeset to bumb up minor version.
After that, I ran `changeset version` to bump up packages version. 
I expected the pacakge's versions were bumped up as `v1.1.0 `each. But they were turned into `v2.0.0.`

What is problem?

**Comment by Andarist** [comment]
Please share a runnable repro case. It's hard to tell what is wrong in your case. Perhaps some of your packages are used as peer dependencies?

**Comment by Andarist** [comment]
You can change the behavior around this using this flag in the config:
```json
  "___experimentalUnsafeOptions_WILL_CHANGE_IN_PATCH": {
    "onlyUpdatePeerDependentsWhenOutOfRange": true
  }
```

**Comment by unional** [comment]
> You can change the behavior around this using this flag in the config:

Note that seems like it is not working in 2.25.0
