### ISSUE TITLE
Change icon for non toggled cli options to red cross (a11y issue)

### ISSUE THREAD

**Issue by basickarl** [changesets/changesets#971]
`"@changesets/cli": "^2.22.0",`

When trying to toggle whether or not a package is to be included in a changeset in some terminal windows (the one in vscode for example) the unselected green and selected green are hardly different and it is very hard to see what has been accepted:

Unselected:
<img width="234" alt="Screenshot 2022-10-05 at 17 12 18" src="https://user-images.githubusercontent.com/10507098/194096790-bb6e409c-4912-4873-a442-0d8a87c0abc2.png">

Selected:
<img width="289" alt="Screenshot 2022-10-05 at 17 12 24" src="https://user-images.githubusercontent.com/10507098/194096813-97abfb24-29a7-443e-bebf-0d22b6713df1.png">

I suggest changing the icon to a red X, this won't only fix issues for certain terminals but for color blind people in general.

**Comment by Andarist** [comment]
I would happily review a PR to improve this situation. Actually, we were adjusting those things somewhat recently - the previous related PR can be found here: https://github.com/changesets/changesets/pull/811 . So perhaps you could prepare a new one that would adjust those places in the code?

**Comment by basickarl** [comment]
Yapp that was the solution! It's looking great now after the merge.
