### ISSUE TITLE
changeset publish is failed, Received 404 for npm info

### ISSUE THREAD

**Issue by i7eo** [changesets/changesets#987]
## Affected Packages

`@mercur1/hooks`
`@mercur1/ui`
`@mercur1/request`
`@mercur1/ui-pro`
`@mercur1/tokens`
`@mercur1/directives`
`@mercur1/utils`

## Problem

1. execute `pnpm changeset:gen` to create changeset.
2. `git add . && pnpm commit && git push`
3. execute github action `release.yml`

You can see https://github.com/casta-fe/mercury-monorepo/actions/runs/3313242853/jobs/5470954044#step:11:14

## Proposed solution

Hope `pnpm exec changeset publish` is success, and publish packages

When i publish first time, this always return `E404`.

```
// cli.esm.js

// ...

let result = await spawn$1("npm", ["info", packageJson.name, "--registry", getCorrectRegistry(packageJson), "--json"]); 

//...
```

**Comment by i7eo** [comment]
I assure  I set up npm token with github token the right way.🌚

**Comment by i7eo** [comment]
I created these `@mercur1/hooks @mercur1/ui @mercur1/request @mercur1/ui-pro @mercur1/tokens @mercur1/directives @mercur1/utils` manually. 

Then i trigger GitHub Action `release.yml`, report errors. see https://github.com/casta-fe/mercury-monorepo/actions/runs/3313419924/jobs/5471372831#step:11:17

This confused me and I really didn't know what to do. Can u look this? @Andarist

**Comment by Ethan-Arrowood** [comment]
I think I hit this too: https://github.com/jsperfdev/jsperf.dev/actions/runs/3318479793/jobs/5482470942#step:6:34

Was able to run command locally and publish with no problem. I wish changeset would've shared more of the error as theres not much of anything to act off of here.

**Comment by i7eo** [comment]
> I think I hit this too: https://github.com/jsperfdev/jsperf.dev/actions/runs/3318479793/jobs/5482470942#step:6:34
> 
> Was able to run command locally and publish with no problem. I wish changeset would've shared more of the error as theres not much of anything to act off of here.

😂

**Comment by i7eo** [comment]
Hi @Ethan-Arrowood . I resolve this mistake.

In my case, i install my sub package into other sub package `devDependencies`. When i put these to `dependencies`, mistake disappear. I don't know what happened🥱.

I can give you a few suggestions:

-  Check for `''private": true` package, add `''version': "0.0.0"`
- Put interdependent packages under `dependencies` instead of `devDependencies`

**Comment by shaobeichen** [comment]
In my case, `workspace:*` change to `workspace: *`, it work.
